### ISSUE TITLE
Be able to add a css class to the target container

### ISSUE THREAD

**Issue by Hyzual** [luckylooke/dragular#100]
Hi,

I'd like to submit a feature request. Using dragular, it is possible to customize the mirror element that you're dragging with the CSS class `gu-mirror`. It would be great to be able to add a CSS class to the container that we're about to drop into.

### What is the use case behind this ?

In our tool's UX, we make a distinction between empty containers and containers with items in them. We usually add a background image to show users that the container is empty but that you can drop items in it. Having a custom CSS class on the container would let us change the background image or the background color of our container so that the user knows the drop she's about to make is taken into account. See the images below for an example with a Kanban app we're building:

This is what our empty container looks like:
![Empty container](https://cloud.githubusercontent.com/assets/2051507/17327050/bc96c618-58b5-11e6-9dae-5562613f7e48.png)

This is what happens when the CSS class on the container is added:
![Empty container with drop incoming](https://cloud.githubusercontent.com/assets/2051507/17326888/b0277ebe-58b4-11e6-8c53-4b1a1217da8e.png)

FYI this feature would be "syntactic sugar", it's already possible to do so using dragular's events `dragularenter`, `dragularleave` and `dragularrelease`. What do you think about it ?

**Comment by luckylooke** [comment]
It is already posible.. Dragular emits custom DOM events on elements behind  dragging item. You can hook on them.
```js
 angular.element(targetElement).on('dragularenter', function() {
        targetElement.style = mySuperCoolStyle;
      });
      angular.element(targetElement).on('dragularleave dragularrelease', function() {
        targetElement.style = originalStyle;
      });
```
Reopen if it is not suitable for your use case. ;)
