### ISSUE TITLE
Clone dragged element before applying gu-transit class

### ISSUE THREAD

**Issue by Hyzual** [luckylooke/dragular#101]
Hi again,

I have found an odd behavior that I wanted to share with you. In our app, we don't keep the `gu-transit` element's "transparent" appearance, and instead we style it to appear as a colored "line". We therefore change its height to about 6px. When I drag an item, the `gu-mirror` cloned element will have an odd style with borders not being the same size as the background (see the screenshot below). When I inspect the item, it turns out that the `gu-mirror` will have its height set to 6px directly as a CSS style on the element.

Here, I would expect the `<li>` I've selected to have about the same size as the item I'm dragging (down to "Assigned to"):
![odd style for gu-mirror](https://cloud.githubusercontent.com/assets/2051507/17328281/041f2eba-58bd-11e6-9e0e-32264d9a4e91.png)

I've tried following the code that brings this situation but didn't go as far as I wanted. I suspect that cloning the dragged element is done *after* having applied the `gu-transit` class, leading to this situation where the mirror takes the height of the `gu-transit` class when I would expect it to take the height of the "normal" element.

### Existing workaround

I've nonetheless found a workaround for this. In our HTML structure, containers are `<ul>`s and list items are `<li>`s containing `<div>`s and a whole tree of tags under them. It turns out that when you apply background and border styles to the inner `<div>` instead of the `<li>` that is actually being dragged, the style looks okay even though the `<li>`'s height is still about 6px.

In order to avoid this behavior, I suggest cloning the dragged element (creating the mirror) to take place _before_ applying the `gu-transit` class to the dragged element. What do you think about it ?

**Comment by luckylooke** [comment]
Thanks for cooperation and elaboration of solution, i will apply it in next release. Hopefully in a week.

**Comment by luckylooke** [comment]
Fixed in dev branch, will be in next release soon. It was not true bug but more like improvement request, so I have removed the label. Thank you @Hyzual for your contribution! :)
