### ISSUE TITLE
exampleDirectiveWithModel

### ISSUE THREAD

**Issue by sreejajose** [luckylooke/dragular#105]
Can someone please help me to use dragular with dragular-model, without DOM manipulation using queryselector and angular.element? 

http://luckylooke.github.io/dragular/#/docs/exampleDirectiveWithModel

i get errors when i am using dragular-item with dragular-model?

**Comment by sreejajose** [comment]
Issue: When I am loading a list dynamically example $scope.models.alarmRelay1List.push(alarm), and when I am dragging it to the container, it is dragging the desired element. But when I finally drop it, its dropping the next element, instead of the first element. This happens when I am using Dragular-model.

If I am using DOM manipulation, Dragular is working fine.
Also it is coming only for the list I am using push(), other lists are dragging the correct element.

**Comment by luckylooke** [comment]
Please try to edit [this fiddle](https://jsfiddle.net/hLsuege1/) to reproduce your problem, thanks.

**Comment by luckylooke** [comment]
Closed as inactive
