### ISSUE TITLE
Dragging doesn't work in IE9

### ISSUE THREAD

**Issue by ipavlic** [luckylooke/dragular#107]
Nothing on the demo page works on IE9.

**Comment by luckylooke** [comment]
I will look at it soon.. need to borrow PC! Thanks for report.

**Comment by ipavlic** [comment]
Microsoft has free virtual machines with Internet Explorers from 8 onwards: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

They offer multiple platforms, like VirtualBox, Vagrant, VMWare or Parallels. So regardless of your system, you can use the appropriate IE version. And with https://ngrok.com/, you can easily tunnel to localhost.

**Comment by luckylooke** [comment]
I dont believe virtual machines, I have multiple bad experience with them. They worked differently from real machines and I burn lot of hours finding that it was the only reason some stuff didnt work. I rather borrow pc for a while ;) But anyway, thanks for links and advice 👍

**Comment by ipavlic** [comment]
I would agree for some lower level work, but in this case, the issue is several layers of abstraction above that (e.g. Windows > IE > JS engine). Shout if I can help anyhow.

**Comment by luckylooke** [comment]
Is there a free solution I can run those virtual machines on Mac?? Thanks

**Comment by ipavlic** [comment]
Sure, I'm running them with VirtualBox.

**Comment by luckylooke** [comment]
I dont know why I didnt try to look at virtualbox Mac version, I have used virtualbox in several linux distributions and on win too. Ok, now I am downloading VM with IE9. I hope I will be able to debug in IE :D I dont have much experience with IE tools. Wish me a luck ;)

**Comment by luckylooke** [comment]
Fix based on [dragula issue](https://github.com/bevacqua/dragula/issues/261)! Thanks for contribution! ;)
