### ISSUE TITLE
Does not work with Webpack and strict mode.

### ISSUE THREAD

**Issue by DannyMoerkerke** [luckylooke/dragular#108]
When bundled with Webpack together with other code that uses `use strict;` the error `Cannot read property 'navigator' of undefined` appears.

This is because there is a `global` variable that refers to `this` which is undefined in strict mode.
In `/dist/dragular.js` line 1329 reads:

```
/* WEBPACK VAR INJECTION */}.call(exports, (function() { return this; }())))
```

but this should be:

```
/* WEBPACK VAR INJECTION */}.call(exports, (function() { return window; }())))
```

I would be happy to solve this with a pull request but I am not sure if this is added by Webpack in your build somehow.

**Comment by luckylooke** [comment]
Added by webpack, I will try ti find out why.. thanks for report.

**Comment by luckylooke** [comment]
I was googling about this issue, but havent found solution so far, can anybody help me with this issue? Thanks

**Comment by luckylooke** [comment]
Please try to replace all 'global.navigator' in source code with 'window.navigator' and test it please, thanks

**Comment by DannyMoerkerke** [comment]
I can confirm that replacing `global.navigator` with `window.navigator` works, but the issue is that Webpack appears to injects this code, possible deriving things from the Dragular source code (?)
So far, I haven't experienced this problem when bundling other code.

**Comment by luckylooke** [comment]
Ok so replacing replacing global.navigator with window.navigator in source code of dragular is solution for this issue as I understand.

**Comment by DannyMoerkerke** [comment]
Yes I think that will be the case.
