### ISSUE TITLE
Can not use ng-repeat on container

### ISSUE THREAD

**Issue by desatir7316** [luckylooke/dragular#109]
Hi
thank you for your good module, how can i use ng-repeat on container div? i want to my have number of containers equals to array length.

thanks in advance.

**Comment by luckylooke** [comment]
Something like this? http://luckylooke.github.io/dragular/#/docs/exampleNestedNgRepeatWithModel

**Comment by desatir7316** [comment]
Thanks, it seems great.
Another problem is that I load my data from a service and it not work for me. I also tried to append my service data to example, it only work for example rows and my added data will not move(from row 4 in this example: http://luckylooke.github.io/dragular/#/docs/exampleNestedNgRepeatWithModel)
