### ISSUE TITLE
Feature request: limit items to be dropped in a list

### ISSUE THREAD

**Issue by rbatllet** [luckylooke/dragular#11]
I need to avoid adding more then x elements in a list. It would be great if it's configurable.

**Comment by jameswyse** [comment]
You can do this with the `accepts` option

```js
accepts: function (el, target, source, sibling) {
  return target.children.length < 5;
}
```

Demo: http://codepen.io/jameswyse/pen/JdBPJd

**Comment by luckylooke** [comment]
@jameswyse solution is sufficient enough, so implementing feature is not necessary.
