### ISSUE TITLE
Change data structure during drags

### ISSUE THREAD

**Issue by desatir7316** [luckylooke/dragular#110]
Hi
Thanks for you useful module.
I send a request by each drag and want to update my $scope.items model, I mean I want to update tags on  my page also. How should I do so?

thanks in advance.

**Comment by desatir7316** [comment]
any help?

**Comment by luckylooke** [comment]
If you want me to help you, prepare scenario on codepen/fiddle/bin/... and describe what you expect and what id does, thanks

**Comment by luckylooke** [comment]
Closing as inactive
