### ISSUE TITLE
Free Move

### ISSUE THREAD

**Issue by adelemam** [luckylooke/dragular#111]
I am looking for a feature where there can be containers with free move items ( not just re-ordering ) like interact.js [http://interactjs.io/]

Is there is any possibility to accomplish that, as combining two scripts are a difficult.

**Comment by luckylooke** [comment]
I thnik it is not possible right now.. but I will be thinking about solution for a while (few days)

**Comment by luckylooke** [comment]
I ve got idea, I think it is possible, could you prepare some simulation of your enviroment on codepen/fiddle/bin/... and send me link, I can show you how you can do it then. Thanks

**Comment by adelemam** [comment]
can you tell me exactly what I have to do :)  , As I have no idea, 
all I want is two containers one sorted and the other one like canvas , If i moved from canvas to sorted it will be sorted normally , if from sorted view to canvas  it will add in absolute positioning.

thanks a lot:)

**Comment by luckylooke** [comment]
You can do that, just make one container with css style that children are absolutely positioned inside that container and after placing items into it get x,y coordinates from dragulardrop event and apply them to placed element, thats all. ;)
