### ISSUE TITLE
Multiple drag and drop (with effects)

### ISSUE THREAD

**Issue by pb91** [luckylooke/dragular#112]
Please help me out with multiple drag and drop .

Note : Please reply asap as it is very urgent to deliver.

**Comment by luckylooke** [comment]
If you want me to help you, prepare scenario on codepen/fiddle/bin/... and describe what you expect and what id does, thanks

**Comment by pb91** [comment]
Thanks @luckylooke . 

http://stackoverflow.com/q/40595459

**Comment by pb91** [comment]
I'll write to this thread only if i need your help in future.
