### ISSUE TITLE
Check if element being dragged is over a particular container in markup

### ISSUE THREAD

**Issue by jamielovelace** [luckylooke/dragular#114]
Is this possible? 

I was wondering if you could check if an element is being dragged into a particular container so you could change the markup of the item being dragged, e.g

```
    <div id="container1">
        <div ng-repeat="item in items">{{item.value1}}</div>
    </div>
    <div id="container2">
        <div ng-repeat="item in draggedItems">
            <p>{{item.value1}}</p>
            <div ng-bind-html="{{item.html}}"></div>
        </div>
    </div>
```

The default way will just put the container1 markup into container2 when dragging, was wondering if its possible to put the container2 markup in whilst its in transit?

At the moment I have both sets of markup in the 'container1' and just display none / display block when it has the class of gu-transit - which works fine, I was just wondering if there is a more efficient way.

**Comment by luckylooke** [comment]
Sorry for late answer I have been busy these days.. yes it is possible, you can use dragular DOM custom Events (**dragularenter, dragularleave, dragularrelease**), they are fired on elements underneath of dragging cursor. I am using them to scroll container via dragging in [this example](http://luckylooke.github.io/dragular/#/docs/exampleScrollingDrag).

**Comment by jamielovelace** [comment]
Perfect thats what I was looking for thanks
