### ISSUE TITLE
Mobile Scroll Problem

### ISSUE THREAD

**Issue by akautsar** [luckylooke/dragular#116]
I have some problem when scrolling thru mobile browser (Blackberry Q10 - Stock Browser). Instead of scrolling the page it's just switching position between image (drag n drop) action.

My question, is it possible to delay drag n drop action and do scrolling.

Here is my plunker: https://plnkr.co/edit/eScMnF3aYiko7JIy0Ic1?p=preview
Plunker run url on browswer mobile devices: https://run.plnkr.co/DWNcSv9ljwnPE1sZ/

Thank you very much for your time and the library

**Comment by luckylooke** [comment]
Sorry for later answer I have had busy days.. I have answered your question on [stackoverflow](http://stackoverflow.com/questions/41440127/mobile-scroll-using-dragular-on-angularjs/41543251#41543251), please confirm if it is OK for you, thanks ;)

**Comment by luckylooke** [comment]
You accepted the answer on stackoverflow so I assume this as closed, if any further questions, don't hesitate to write here or on stackoverflow. Thanks

**Comment by januslo** [comment]
hi @luckylooke, I occurs the same thing here and checked your answer in stackoverflow already. Your first solution is not acceptable for the desgin problems. I have tried your second one but found  drake.start(element) not works as propers, would you please help to provide some sample in nasty drag situation about this.? thx a lot.

**Comment by luckylooke** [comment]
@januslo what about this [DEMO](http://luckylooke.github.io/dragular/#/docs/exampleScrollingDrag)? It is solution for you?

**Comment by januslo** [comment]
@luckylooke  seams is not the same problem we are talking about. I think the owner was asking about the misfire issue of the position swap by the drag which propers one scrolling the page simply. In my case, I wanna a hold action to trigger the position swap, otherwise, i want the drag to control the page scrolling only. Is my description clear enough ?

**Comment by januslo** [comment]
@luckylooke , after some testing, i found the manualStart just trigger the start function but not listening the mouse move event. I modified the code and found it works well.
` function manualStart(item) {
	      var context = canStart(item);
	      if (context) {
          /** my modifications **/
          shared.grabbed = context;
          eventualMovements();
	      //  start(context);
  /** my modifications end **/
	      }
	    }`
