### ISSUE TITLE
Dragging with data change does not bind with drag events

### ISSUE THREAD

**Issue by mykevin81** [luckylooke/dragular#117]
Hi!

I am trying to create a form generator with your drag event.
It is a nested ng-repeat for rows and dynamic width columns.

My issue is that I'm also trying to add a functionality of template that can be dragged onto this form, and create multiple rows in one drag. (which means the template data should go into the original acceptable data and follow it's format.)

The original acceptable data is as follows:
```
[
  {
    "row": [
      {
        "col": {
          "id": "1",
          "name": "Text Input",
          "category": "Default",
          "question": null,
          "divtype": "TextInput",
          "repeat": [],
          "detail": null,
          "answer": "",
          "flex": 40,
          "align": "start",
          "orientation": "row"
        }
      },
      {
        "col": {
          "id": "1",
          "name": "Text Input",
          "category": "Default",
          "question": null,
          "divtype": "TextInput",
          "repeat": [],
          "detail": null,
          "answer": "",
          "flex": 50,
          "align": "start",
          "orientation": "row"
        }
      }
    ]
  },
  {
    "row": [
      {
        "col": {
          "id": "4",
          "name": "Check Box",
          "category": "Default",
          "question": null,
          "divtype": "CheckBox",
          "repeat": [],
          "detail": null,
          "answer": "",
          "flex": 0,
          "align": "start",
          "orientation": "row"
        }
      }
    ]
  }
]
```

As you can see, the parent dragular is bind to "row" and the child is bind to "col"
The issue is our Template data is stored as follows:
```
{
    "content": [
      {
        "row": [
          {
            "col": {
              "id": "14",
              "name": "Header",
              "category": "Default",
              "question": "SOME PROFILE",
              "divtype": "Label",
              "repeat": [],
              "detail": null,
              "answer": "",
              "flex": 0,
              "align": "start"
            }
          }
        ]
      },
      {
        "row": [
          {
            "col": {
              "id": "13",
              "name": "SubHeader",
              "category": "Default",
              "question": "FIRST LINE.<br>SECOND LINE",
              "divtype": "Label",
              "repeat": [],
              "detail": null,
              "answer": "",
              "flex": 0,
              "align": "start"
            }
          }
        ]
      }
    ],
    "templateName": "SOME PROFILE",
    "templateID": "13"
}
```

As you can see, the Template has a content that wrapped all the rows.

So I wrote a function in `$scope.$on('dragulardrop'....` to change the data after the template got dropped. it is as follows:

```
for (var i = 0; i < $scope.items.length; i++) {

	if ($scope.items[i].content != undefined) {
		var data = $scope.items[i].content;	
		var secondArray = $scope.items.splice(i, $scope.items.length);
		secondArray.splice(0, 1);
		$scope.items = $scope.items.concat(data);
		$scope.items = $scope.items.concat(secondArray);	
	}
}
```
This function provides me with the correct data.
The big issue is that, after the data changes, I am able to see all of them. But the rows comming from template did not bind to the dragular service. hence, they are unable to be dragged around.

Am I doing something wrong? Is there a way to reinitialize the model that binds to the dragular service?

Thanks.

**Comment by luckylooke** [comment]
This is very common mistake with the library, when you initialize containers with dragularService or vie directive you are providing model representing data via options.containersModel. The lib is taking a reference to that object and use it as model.

By `$scope.items = $scope.items.concat(data);` you are replacing array `items` with new array in $scope object, but libary still keeps reference to original one.

There are at leasr two simple solutions for this.

1. you can push new data to original one:
`[].push.apply($scope.items, data);`

2. I have recently added support for giving a string into `options.containersModel` wich represents property in provided scope object via `options.scope`
`{containersModel: 'items', scope: $scope}`

Try one and let me know if it worked for you. Thanks

**Comment by mykevin81** [comment]
Wow! I didn't know that!

This is what I did to change $scope.items

```
$scope.formatData = function() {
		
	for (var i = 0; i < $scope.items.length; i++) {

		if ($scope.items[i].content != undefined) {
			var data = $scope.items[i].content;	
			//remove original item
			$scope.items.splice(i, 1);

			//go through each of the var data and insert into where it should be
			for (var j = 0; j < data.length; j++) {
				//console.log(data[j]);
				$scope.items.splice(i, 0, data[j]);
				i++;
			}	
		}
	}	
};
```

Thank you so much, I've learned something!
And your dragular saved my life! #

**Comment by luckylooke** [comment]
I am glad you like using dragular 👍
