### ISSUE TITLE
Dropzone

### ISSUE THREAD

**Issue by Myrdivar** [luckylooke/dragular#118]
Hi,

Is there a way to simulate a dropzone behavior? An orgin container that allow the items to be moved away (and not dropped into another position of the container) and to be dropped in a container that will show no shadow and that will not accept the item.

Thanks!

**Comment by luckylooke** [comment]
Yes it is possible, see example here: http://luckylooke.github.io/dragular/#/docs/exampleIsContainerWithModel

But current version have some bug, so ii isnt working, I will fix it as soon as possible, since then you can try it with older version. Thanks for understanding.

**Comment by luckylooke** [comment]
OK, I have fixed it, so example now works with latest release ;)

**Comment by Myrdivar** [comment]
Great!

By mixing the example you've suggested with this one:
http://luckylooke.github.io/dragular/#/docs/exampleDragOverEvents

I was able to reproduce the effect.

Thanks for the help (and by the way... great library!!)

**Comment by luckylooke** [comment]
Thanks :)
