### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by alferov** [luckylooke/dragular#12]
Hi, are you planning to write tests?

**Comment by luckylooke** [comment]
Yep, just planning :D If you would like to write them, that would be awsome!!! :)

**Comment by alferov** [comment]
:+1:
I don't mind to :smile: 
What about workflow automation?
Would you like me to setup gulp environment (based on your current node scripts)?

**Comment by luckylooke** [comment]
It would be nice. I feel better about editing and modifing gulp workflow..
rather than npm.

**Comment by luckylooke** [comment]
I have noticed that original dragula have many tests already written, so they can be copied/modified ;)

**Comment by alferov** [comment]
Oh, right.
Last time I checked it out there were no tests at all.

**Comment by luckylooke** [comment]
Yes they put it there recently.. ;-)
