### ISSUE TITLE
[question]Cannot understood button detect mechanism in function whichMouseButton of dragularService.js

### ISSUE THREAD

**Issue by januslo** [luckylooke/dragular#125]
Since the parameter is unwrapped to orginalEvent object, I cannot understood the mechanism in function wichMouseButton, referring https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button , value 0 should be a valid in drag but is ignored by function startBecauseMouseMoved; besides, the priority of button property may higher then buttons since most of the browers are support button rather then buttons.

**Comment by luckylooke** [comment]
yeah, I havent revised this functionality for a while, and it was originally taken from dragula, so I accept your pull request as it seams to be OK
