### ISSUE TITLE
Accept or canBeAccepted not working with isContainer and IsModel : Dragular

### ISSUE THREAD

**Issue by pb91** [luckylooke/dragular#128]
Scenario 1 : Using two container lets say A(Drag Source) and B(Drop Source).

Code snippet :

  ```
dragularService(containerLeft, {
      containersModel: [DragularconTainer],
      copy: true,
      canBeAccepted: function(el, source) {
        var elementDrag = angular.element(el)
        return false;
      },
      revertOnSpill: true,
      isContainer: function isContainer(el) {
        return el.id === 'filler';
      },
      isContainerModel: function getModel() {
        return $scope.TestModel;
      },
      scope: $scope
    }); 
``` 
Scenario 2 : Using B(Drop Source) for nested drag and drop in between.

     var container = containerRight,
          parentContainers = container.children(),
          nestedContainers = [];
        console.log(parentContainers);
        console.log($element.children());
        dragularService(container, {
          revertOnSpill: true,
          moves: function(el, container, handle) {
            return handle.classList.contains('row-handle');
          },
          containersModel: $scope.object,
          nameSpace: 'rows'
        });

        // collect nested contianers
        for (var i = 0; i < parentContainers.length; i++) {
          nestedContainers.push(parentContainers.eq(i).children()[1]);
        }

        dragularService(nestedContainers, {
          revertOnSpill: true,
          moves: function(el, container, handle) {
            return !handle.classList.contains('row-handle');
          },
          containersModel: (function getNestedContainersModel() {
            var parent = $scope.objects,
              containersModel = [];
            for (var i = 0; i < parent.length; i++) {
              containersModel.push(parent[i].test);
            }
            return containersModel;
          })(),
          nameSpace: 'cells'
        });
Issues : Scenario 1 "canBeAccepted : " is not working when used along with isContainerModel. It should work according to Boolean values returned to the function.

Validation: 1. The approach for using container B as drop zone and nested drag.

Please suggest.

**Comment by luckylooke** [comment]
Scenario 1 
``` 
canBeAccepted: function(el, source) {
      var elementDrag = angular.element(el)
      return false;
    },
```
Always returning false, never get accepted.

On scenario, please describe what do you expect, and what it actually does. 

For better and much faster solution of your problems, please reproduce your scenarios in jsfiddle, or codepen .. etc .. somewhere public. It will be then solved asap, thanks for understanding ;)

PS: you can use [this fiddle](https://jsfiddle.net/luckylooke/gmaogwzn/2/) as starting point for you problem reproducing.

**Comment by pb91** [comment]
Thanks @luckylooke  for your response. I have updated the fiddle [this](https://jsfiddle.net/gmaogwzn/6/).

Requirement is - if return is false for CanBeAccepted then the drag item shouldn't be dropped. 
Please let me know if anything else is required.

**Comment by luckylooke** [comment]
I will look at it soon. Thanks for understanding

**Comment by pb91** [comment]
Thanks @luckylooke for coming back on this. I am sure  you will clear this soon :) .

**Comment by luckylooke** [comment]
There was a bug on canBeAccepted in combination with isContainer, fixed now, will be released soon

**Comment by luckylooke** [comment]
@pb91 scenario2 is still the issue for you? If so.. can you please make a fiddle? Thanks

**Comment by pb91** [comment]
in 2nd  scenario i don't have any issues for now but when container for second case keep on updating i am getting => Bug: Uncaught TypeError: Cannot read property 'fm' of null #129 

Just a question .. How to reinitialize the container or service for scenario 2  to remove #129 . 

If you can create any fiddle/code pen for that 

` var container = containerRight,
      parentContainers = container.children(),
      nestedContainers = [];
    console.log(parentContainers);
    console.log($element.children());
    dragularService(container, {
      revertOnSpill: true,
      moves: function(el, container, handle) {
        return handle.classList.contains('row-handle');
      },
      containersModel: $scope.object,
      nameSpace: 'rows'
    });

    // collect nested contianers
    for (var i = 0; i < parentContainers.length; i++) {
      nestedContainers.push(parentContainers.eq(i).children()[1]);
    }

    dragularService(nestedContainers, {
      revertOnSpill: true,
      moves: function(el, container, handle) {
        return !handle.classList.contains('row-handle');
      },
      containersModel: (function getNestedContainersModel() {
        var parent = $scope.objects,
          containersModel = [];
        for (var i = 0; i < parent.length; i++) {
          containersModel.push(parent[i].test);
        }
        return containersModel;
      })(),
      nameSpace: 'cells'
    });`

**Comment by pb91** [comment]
And please let me know when can you release so i can check the effects. Thanks for understanding. 
--Its kinda very important-- :) :+1:

**Comment by luckylooke** [comment]
In a minutes ;) Feel free to open new issue with reproduced problem in a fiddle if fixes wont solve your issues. Thanks

**Comment by luckylooke** [comment]
Released: https://github.com/luckylooke/dragular/releases/tag/v4.3.4
