### ISSUE TITLE
Bug: Uncaught TypeError: Cannot read property 'fm' of null

### ISSUE THREAD

**Issue by phazei** [luckylooke/dragular#129]
Full error:
dragular.js:681 Uncaught TypeError: Cannot read property 'fm' of null
    at drop (dragular.js:681)
    at cancel (dragular.js:786)
    at HTMLHtmlElement.release (dragular.js:450)
    at HTMLHtmlElement.dispatch (jquery.js:4737)
    at HTMLHtmlElement.elemData.handle (jquery.js:4549)

Using:
Ubuntu 16.04, Chrome v58

To reproduce:
http://luckylooke.github.io/dragular/#/docs/exampleBasicWithModel
Drag the second item out of the boxes a couple times.  Once you let go of the mouse, it will stay 'stuck' to the mouse till you drop it in one of the box.  Doesn't seem to happen on the first item.  I noticed this in my app and it reproduces in the demos.

**Comment by luckylooke** [comment]
Fixed, will be in next release ;)

**Comment by luckylooke** [comment]
Released: https://github.com/luckylooke/dragular/releases/tag/v4.3.4
