### ISSUE TITLE
unable to cancel drag with model in events

### ISSUE THREAD

**Issue by phazei** [luckylooke/dragular#130]
Not sure if I'm going about this the proper way, but I don't see any other.
I'm using dragular with models.

If drake.cancel(true) is called in the 'dragulardrop' event, if I step through, after the .cancel call, it shows in the right place, but it doesn't actually revert the move in the sourceModel or targetModel, so when it redraws the ng-repeat, it isn't reverted at all.

If drake.cancel(true) is called in the 'dragulardrag' event it doesn't move, but it throws the error:

```
dragular.js:1311 Uncaught TypeError: Cannot read property 'parentNode' of null
    at getParent (dragular.js:1311)
    at HTMLHtmlElement.startBecauseMouseMoved (dragular.js:553)
    at HTMLHtmlElement.dispatch (jquery.js:4737)
    at HTMLHtmlElement.elemData.handle (jquery.js:4549)
    at HTMLHtmlElement.a.bugsnag (bugsnag-2.min.js:1)
```

**Comment by phazei** [comment]
The reason it's important to be able to cancel on drag or drop is validation.  The boxes have both a min and a max number of items they can accept, if they drop it and there are too many, I want to revert and show a flash message.  Can't do that.  If they try to drag and there aren't enough, it does prevent it, but it throws that parentNode error.

**Comment by luckylooke** [comment]
Ok, I will look at drake.cancel(true) soon.. it seems to be a buggy, I wasnt using that method in my projects (it was taken from dragula), but I think I can fix it easily.. you can also put your accepting/not accepting logic into [option.accepts](https://github.com/luckylooke/dragular#optionsaccepts) fn

**Comment by luckylooke** [comment]
I have fixed the dragulardrag  part.. but the second part will remain untouched. The drake.cancel() is not meant to be undo(), it is meant to be method for canceling actual drag, so dont use it after drop. You can put logic into accept or canBeAccepted as I mentioned before to prevent dropping the item.
