### ISSUE TITLE
odd scrolling on mobile when attempting to drag

### ISSUE THREAD

**Issue by phazei** [luckylooke/dragular#131]
I don't know if #126 was trying to fix this or caused it, but scrolling on mobile is weird.  If I click an item to drag, if I drag it up and down, it takes the screen and scrolls it too.
Happens here:
http://luckylooke.github.io/dragular/#/docs/exampleBasicWithModel

**Comment by phazei** [comment]
It leaves these two warnings in chrome that could be the cause:

```
dragular.js:575 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080
startBecauseMouseMoved @ dragular.js:575
dispatch @ jquery.js:4737
elemData.handle @ jquery.js:4549

dragular.js:1190 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080
```

**Comment by phazei** [comment]
Don't think it was the PR at all, in the last few versions of chrome, they changed the way you need to prevent default for scrolling.

**Comment by phazei** [comment]
https://github.com/alvarotrigo/fullPage.js/issues/2362
https://github.com/dimsemenov/PhotoSwipe/issues/1217

A bit more insight to this there.  From Chrome 56 on they made a breaking change to [improve scrolling](https://developers.google.com/web/updates/2017/01/scrolling-intervention)...

Apparently can be fixed with touch-action css

**Comment by luckylooke** [comment]
Yes it was working fine before... so it seems that the change you mentioned affected dragular, I will look at it asap (in few days I hope).. thanks for your report and suggestions! ;)

**Comment by luckylooke** [comment]
fixed, will be in next release asap ;)

**Comment by luckylooke** [comment]
Released: https://github.com/luckylooke/dragular/releases/tag/v4.3.4

**Comment by phazei** [comment]
Thank you so much, awesome that you got to all the issues I reported so quickly.  Great package, thanks for all the hard work :D

**Comment by luckylooke** [comment]
Yeah, I was sad that the lib looked to be so buggy, so it push me to solve everything asap :D But there is still one bug on IE which is still making me sad, bud I have no extra energy for IE now..
