### ISSUE TITLE
Drag and drop using isContainer and models not working with new release  4.3.4

### ISSUE THREAD

**Issue by pb91** [luckylooke/dragular#132]
FYR - [Fiddle Link ](https://jsfiddle.net/gmaogwzn/6/)

Please look into this.

**Comment by luckylooke** [comment]
🤕 .. it is for isContainer() case only, other cases are working, see DEMO.. but anyway, yesterday I was fixing some stuff and I forgot that there was PR to master branch and merging it was painful, and seems that not 100% successful. I will fix it in the evening and release new one, then. Thanks for understanding.

**Comment by luckylooke** [comment]
You can check your fiddle now it works perfectly, try to edit `canBeAccepted` to accepts `card` elements and they can be dropped.
