### ISSUE TITLE
How to dynamically add containers ?

### ISSUE THREAD

**Issue by JerimSD** [luckylooke/dragular#135]
Hi, it's me again. ><

I'm still working with your library. I have a nested structure of Rows and Columns dynamically generated with ngRepeats. I can drag and drop the columns to reorganize them inside their original row or to move them to another row.
I recently added a feature to dynamically add new rows. But when I add one, I can't drag any column from the last row or drop any column into it either.

When I call the Service for the Columns, I provide an Array of all the column containers. So when I add a new Row (ie, a new column container) I push the new element into that Array to tell the service that a new container should be handled. But it doesn't seem to be enough. I don't get what I'm doing wrong.

![chrome_2017-04-10_16-42-36](https://cloud.githubusercontent.com/assets/14279682/24868022/255b864c-1e0f-11e7-8ca7-8d83b07cdfe9.png)

Here's another Plunker where I'm trying to make it work : https://plnkr.co/edit/YfQGYCsdZkWTGbdCRXTk

Anyway, great work on this library overall.

**Comment by luckylooke** [comment]
hmm.. interesting... should be working... I havent start fixing your issues yet, I have some finishing stuff on other project I need to close soon. :/ I do my best to get over it and start fixing dragular asap. Thanks for patience!

**Comment by luckylooke** [comment]
I have fixed this by allowing containers to be a function returning array or arraylike object (DOMcollection, jQueryCollection, ..), will be in next release, but #133 is still the issue, which seems to become long term problem for now.

**Comment by JerimSD** [comment]
Unfortunately I won't be able to work on the project for a few weeks.
I'll ask a colleague to take care of this for me and I'll give you feedback myself as soon as possible.
Thank you very much for fixing that issue.
