### ISSUE TITLE
dynamic model via directive doesn't work properly

### ISSUE THREAD

**Issue by mih-kopylov** [luckylooke/dragular#138]
There're several bugs:
- when dynamicModelAttribute is set, it adds $watch for evaluated `$scope.$eval(attributes.dragularModel)` and in apply function there's second evaluation: `drake.sanitizeContainersModel( $scope.$eval( newVal ) )`. Obviously when I have expression `dragular-model="data.model"`, it's evaluated to array in $watch, and then it tries to evaluate the array again.
- the result of the evaluation is set to `drake.containersModel`, but this property of `drake` isn't used in `dragularService`, private variable `o` - shortland for `options` is used instead

**Comment by luckylooke** [comment]
Should be working correctly now, please update to v4.4.2 and let me know, thank you for your contribution 👍

**Comment by mih-kopylov** [comment]
Works now, great, thanks!
