### ISSUE TITLE
can't drag over list or overflow

### ISSUE THREAD

**Issue by rohitdaryanani** [luckylooke/dragular#14]
Hey I cant seem to drag items if the list is long. the list won't scroll down .

Thanks

**Comment by luckylooke** [comment]
please provide live demo, jsfiddle,jsbin,webpage whatever, then I can see the setup, thanks

**Comment by rohitdaryanani** [comment]
Here's the link http://rohitdaryanani.com/dragular/ .Sorry about that. It’s basically a stripped down version of the example you provided. I just added additional items, set the max height and had an overflow y so it would be scrollable. There are 13 items on the list but initially, it displays only items 1 to 6. I would like to drag item number 1 or 2 to be placed after item number 7 but i can’t seem to scroll when i reach item number 6. Hope this helps, Thanks

**Comment by luckylooke** [comment]
Thanks now I can precisely imagine what is the problem, I will be thinking about solution.

**Comment by luckylooke** [comment]
Interesting is that when I try to scroll while dragging in our demo page, it works fine. I must find out what blocks scrolling in your case.

**Comment by luckylooke** [comment]
I think I have found solution.. but I will implement it later as it needs to change dragular code for it a bit.
```
ghostElm.onwheel = function(e){    
containerElm.scrollTop += e.deltaY;
};
```

**Comment by luckylooke** [comment]
If you need it now, it solved already in [dev branch 'v150'](https://github.com/luckylooke/dragular/tree/v150)

**Comment by rohitdaryanani** [comment]
Hey thanks a lot for this. Works great

**Comment by luckylooke** [comment]
But I havent test it touch device. So if anyone could.. please test it,
thanks ;-)

**Comment by rohitdaryanani** [comment]
Works great on desktop, has issues on ipad it doesn't drag properly will try to post a gif or something.

**Comment by luckylooke** [comment]
I thought so, I will need to make some workaround for touch devices.

**Comment by jameswyse** [comment]
For old browsers you should also listen to the `mousewheel` and 	`DOMMouseScroll` events.
For touch devices you could try playing with the `touchmove`, `touchend`, `scroll` and `gesturechange` events. 

It can be tricky because of the momentum scrolling in iOS etc. calling `preventDefault` in the `touchmove` handler usually helps get immediate feedback (and also prevents the actual scroll)

**Comment by zeeamber** [comment]
scrolling drag is working great with chrome but why its not working with firefox ? 
@luckylooke @rohitdaryanani

**Comment by luckylooke** [comment]
@zeeamber I need to find out but first I need to finish #8 which is more important.

**Comment by luckylooke** [comment]
Should be OK by v2.1.0

**Comment by manuelfink** [comment]
Just looking for the same solution.
Is this yet part of ng2-dragula? 
Can you add docs on how to use/configure this with ng2-dragula?

**Comment by luckylooke** [comment]
I am not watching ng2-dragula but i saw that recently dragula it selves accepted PR related to scrolling, so it is very likely that it will be working in ng2-dragula out of the box after updating dragula dependency.
