### ISSUE TITLE
Changing item value(s) on drop?

### ISSUE THREAD

**Issue by littleginsu** [luckylooke/dragular#141]
I am generating two lists from one object based on a key value (signature). When an item is moved to the other list I need to be able to toggle the signature value. 

I have read through all the Issues and Documentation, and I cannot seem to figure out how to access the object from the dragulardrop event. 

Any help would be greatly appreciated. Thank you in advance.

JSON:
```
[
  {
    "id": 1111,
    "name": "test.txt",
    "desc": "",
    "type": "txt",
    "size": 0,
    "holder": false,
    "required": false,
    "signature": true
  },
  {
    "id": 1112,
    "name": "test.pptx",
    "desc": "",
    "type": "pptx",
    "size": 0,
    "holder": false,
    "required": true,
    "signature": false
  },
  {
    "id": 1113,
    "name": "test.docx",
    "desc": "",
    "type": "docx",
    "size": 0,
    "holder": false,
    "required": true,
    "signature": false
  }
]
``` 

HTML:
```
        <div class="row" ng-controller="FileSort">
            <div class="form-group col-lg-6 col-xl-6">
                <label>Packet Files</label>
                <div class="files" id="packet">
                    <div class="row" ng-repeat="packetfile in npm.fileholders" ng-if="packetfile.signature === false">
                        <div class="file" id="{{packetfile.id}}">
                            <div>
                                <i class="fa" ng-class="npm.fileTypeIcon(packetfile.type)"></i> {{packetfile.name}} ({{packetfile.size}})
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group col-lg-6 col-xl-6">
                <label>Signature Files</label>
                <div class="files" id="signature">
                    <div class="row" ng-repeat="signaturefile in npm.fileholders" ng-if="signaturefile.signature === true">
                        <div class="file" id="{{signaturefile.id}}">
                            <div>
                                <i class="fa" ng-class="npm.fileTypeIcon(signaturefile.type)"></i> {{signaturefile.name}} ({{signaturefile.size}})
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
```

Dragular Controller:
```
    .controller('FileSort', ['$scope', '$element', 'dragularService', function ($scope, $element, dragularService) {
        dragularService('.files', {
            scope: $scope
        });
        $scope.$on('dragulardrag', function (e, el) {
            e.stopPropagation();
            el.className += ' grabbingCursor';
        });
        $scope.$on('dragulardrop', function (e, el) {
            e.stopPropagation();
            el.className = el.className.replace(' grabbingCursor', '');
        });
```

**Comment by luckylooke** [comment]
You can combine last two parameters of dragulardrop event callback function. 7th and 8th parameter target-model and drop-index. You will get item model like this: 
```js

$scope.$on('dragulardrop', function ( e, el, targetContainer, sourceContainer, conModel, elIndex, targetModel, dropIndex ) {
            var itemModel = targetModel[ dropIndex ];
             itemModel.signature = !itemModel.signature;
        });
```

Reference: [https://github.com/luckylooke/dragular#events](https://github.com/luckylooke/dragular#events)

**Comment by littleginsu** [comment]
The targetModel is null.  

I added a {{npm.fileholders | json}} at the bottom of the page like you have in several of your examples, and it is not being updated. The dropIndex and elIndex only appear to correspond with the visual position of the items, not the actual object's index? So I am still unable to reach back to update the object.

I apologize for not being able to set up a live example.. I still very new to using Angular and am not familiar or comfortable with jsFiddle of jsBin. I have included a screenshot of the page, in hopes it might help.

Thank you for your prompt response and in advance for any help you may be able to offer.

![image](https://cloud.githubusercontent.com/assets/26979376/26218445/d7e5ecee-3bbf-11e7-861f-bfe9d477d2a3.png)

**Comment by luckylooke** [comment]
Could you please reproduce the problem somewhere public? Like jsfiddle, codepen, etc.. thank you

**Comment by littleginsu** [comment]
Good Morning, thank you again for you all you help.  I was able to make a live example, although there are some oddities.

https://plnkr.co/edit/9nCakIAIaAYbIIc1mRM7

For instance, I have no idea why the item name is displaying when an item is being dragged; it is not something I have it set up to do. Also, the dropIndex is undefined, however, in my dev environment the dropIndex is the index of the visual position of the dropped item. 

Thank you in advance for any help you may be able to offer.

**Comment by luckylooke** [comment]
You have used old version 3.4.0.. the latest is 4.4.2, you did not provide model to dragular service, so it is why you have undefined index and targetModel.. because dragular works without models when not provided. You need to provide it via options.containersModel. As your situation is quite complicated you need to calculate model for dragular to match the situation from your view (html). Dragular expects model to have same items and order as you have in your html. When you drag n drop element, dragular mimics same movement to models. It is based on indexes. I have edited your plnkr and get this: https://plnkr.co/edit/Gs5Sd3qDSlbZJJXuWOl8?p=preview

there is not perfect solution because item model is dropped into array returned by filter and not into the fileholders array.. maybe would be better to split fileholders into two arrays with and without signature and use those arrays as models and reuse them also in view.

This example on demo page may help you understand: http://luckylooke.github.io/dragular/#/docs/exampleNgRepeatFilteredWithModel

I am not able to help you more, because it is very time consuming and I need that time for developing much better drag n drop library I am working on now. I can help you understand how dragular works, but I cannot solve your usecase for you, thanks for understanding.

**Comment by littleginsu** [comment]
Works perfectly! Thank you so, so much!

**Comment by littleginsu** [comment]
Sorry to bother you again, I have just noticed when I try reordering the items within the same list/container it deletes the item?  

https://plnkr.co/edit/Gs5Sd3qDSlbZJJXuWOl8?p=preview

**Comment by luckylooke** [comment]
should not.. I will look at it soon

**Comment by luckylooke** [comment]
I am sure that there is lution for this, I have to thik about it... but much easier would be to split files into two arrays, each for one container and then if you need to use it together, just merge those arrays back into one. It would simplify the whole setup. If I came with solution without splitting the files array, I will let you know. Anyway, thanks for interesting usecase, I will be thinking about.

**Comment by littleginsu** [comment]
I have done as you suggested and split the array into two.  I followed the [Basic with Model]( http://luckylooke.github.io/dragular/#/docs/exampleBasicWithModel) example and I am still getting the same issue.

https://plnkr.co/edit/9nCakIAIaAYbIIc1mRM7?p=preview

I understand you are very busy and unable to provide support for this usecase, I just wanted to thank you, again, for the time spent troubleshooting this issue.

**Comment by luckylooke** [comment]
I have found the problem.. there is some problem with indexes using ng-if inside ng-repeat :/ I dont know why yet, I will try to find the problem when I would have more time. Thank you for your patience an understanding, and also that you prepared the scenario, so I had more time for focusing on the problem. This is my solution for now, which is not very pretty but it works: https://plnkr.co/edit/Vcky4pispawxlsZcf2La?p=preview

**Comment by luckylooke** [comment]
I am making separate issue for cleaner info, because this issue was about changing the item on drop.

**Comment by littleginsu** [comment]
Thank you so, so much!
