### ISSUE TITLE
How can I drop element from one container to another container's nested array Object?

### ISSUE THREAD

**Issue by AkbarAlam** [luckylooke/dragular#142]
How can I drop element from one container to anothre container's nested array Object?This is one container item

```
 $scope.items1 = [
        {
            'name' : 'x',
            'age' : '4'
        },
        {
            'name' : 'y',
            'age' : '5'
        },
       {
            'name' : 'z',
            'age' : '6'
        }
     ];
```

i want to drop each element in a new container it should be
```
$scope.items2 = [

        {
            'key' : 'info',
            'value' : [ {
            'name' : 'x',
            'age' : '4'
        }]
        },
        {
            'key' : 'info',
            'value' : [ {
            'name' : 'y',
            'age' : '5'
        }]
        },
        {
            'key' : 'info',
            'value' :[ {
            'name' : 'y',
            'age' : '5'
        }]
        },
   

     ];
```
how should i write my **dragularService**

**Comment by luckylooke** [comment]
Hi Akbar,
thanks for using it, I am glad you like it, currently I am working on total rewrite of library, it would be much easier to use/maintain etc...

To your problem.

I need to know exact rules you want achieve.. for example if item from items1 can be dropped between item2 or only inside items2 into values array? Etc..

Please write me all use cases you want to support in your example.

**Comment by AkbarAlam** [comment]
Item1 can be dropped only inside item2 value array. here i am struggling

**Comment by luckylooke** [comment]
I am sorry I am bussy now.. too much deadlines.. :/ Preparing code in jsfiddle, codepen.. or similar is much faster for me to solve problems.. but dont worry, I will answer you soon. It is possible and not so difficult as it looks at the first glance.

**Comment by luckylooke** [comment]
Here is codepen of your case: https://codepen.io/luckylooke/pen/LyoWzR

**Comment by AkbarAlam** [comment]
Thanks but there is a small issue. the value of item 2 should be empty initially.
```
{
  name:'aaa',
  value: [ ]
}
```

 once the  data from item 1 is dropped in item 2 it will go directly in the value. then it should look like 

```
$scope.items2 = [

        {
            'key' : 'info',
            'value' : [ {
            'name' : 'x',
            'age' : '4'
        }]
        },
        {
            'key' : 'info',
            'value' : [ {
            'name' : 'y',
            'age' : '5'
        }]
        },
        {
            'key' : 'info',
            'value' :[ {
            'name' : 'y',
            'age' : '5'
        }]
        },
   

     ];
```

**Comment by luckylooke** [comment]
Oh, I am sorry, I was in a hurry and I made some mistakes.. now fixed in [same codepen](https://codepen.io/luckylooke/pen/LyoWzR). Check it please, if it is OK than please accept also answer [on stackoverflow](https://stackoverflow.com/a/44224830/861615), thanks ;)

**Comment by AkbarAlam** [comment]
Thank you so much. just a question if I want to do it with a model how should I write the service?

**Comment by luckylooke** [comment]
Synced with models: https://codepen.io/luckylooke/pen/KmLGbM?editors=0010

**Comment by AkbarAlam** [comment]
Thank you so much :)
