### ISSUE TITLE
scrolling horizontally on a overflow div

### ISSUE THREAD

**Issue by bmrinal** [luckylooke/dragular#149]
Hi,
This is very similar to this [issue](https://github.com/bevacqua/dragula/issues/121). I need this functionality for a horizontal scroll. Can you provide a nice pointer for the same?

**Comment by luckylooke** [comment]
Please refer to this demo: http://luckylooke.github.io/dragular/#/docs/exampleScrollingDrag, it is vertical scroll example, but horizontal scroll may be created analogical.

**Comment by luckylooke** [comment]
Please feel free reopen the issue if it is still actual, thanks
