### ISSUE TITLE
Model not updated

### ISSUE THREAD

**Issue by albpara** [luckylooke/dragular#152]
I am not sure what I am doing wrong but the model is not being updated when I perform sorting, on the UI the sorting is correctly reflected, no errors

This is my code:

```
dragularService($element.find('.overlay__selector-list'), {
  containersModel: vm.list
});
```

**Comment by luckylooke** [comment]
Code provided looks good... please reproduce the problem somewhere public, so I can see the problem. You can use [this codepen](https://codepen.io/luckylooke/pen/pPmeWY) as starting point.

**Comment by albpara** [comment]
This is a pretty simple example: https://codepen.io/anon/pen/weLNBv

Maybe I am doing something wrong

**Comment by albpara** [comment]
My bad, the problem was the timing, I was calling to dragularService before vm.list had data, in fact I found some curious behavior
