### ISSUE TITLE
Both scopes should be notified about events (source and also target scope)

### ISSUE THREAD

**Issue by orlandovallejos** [luckylooke/dragular#154]
Hello, after doing some tests and research, I want to know if it's possible to drop items to a menu.
This is more or less what I want to do:

![Example](https://d26dzxoao6i3hh.cloudfront.net/items/3T0M3Q2A0Y1q0b3g2U0z/Screen%20recording%202017-07-28%20at%2005.18.23%20PM.gif?v=21db40a7)

I have a menu on the left side(containers), and items on the right side(draggable items). Let's forget about subfolders like in the example.

That would be easy to do... but there's one more requirement. **Those two are in different AngularJS Controllers.**
I added a namespace to the service and I got that working. **But I need to handle the drop event** (which I can't do it right now).

**Note:** As they are different controllers, their scope is different. And they are different "objects",... ones are menu items, and the others are "Person" (or whatever you can imagine), they have different ids, different attributes, etc.

For now, I'm just hiding the dropped items with CSS, but they need to be removed from containers. I don't need that HTML in the menu section.
The menu items are just containers, they should not be draggable.

Here's my codepen: https://codepen.io/orlandovallejos/pen/KvdYaa?editors=1111
Here's the GIF of that pen: 
![What i got](https://d26dzxoao6i3hh.cloudfront.net/items/1x1L0H0H2Y1H1P052N3m/Screen%20recording%202017-07-28%20at%2005.36.25%20PM.gif?v=6e9a7b38)

**Comment by luckylooke** [comment]
Both scopes (provided via options) should be notified, I will fix it soon, until then [here is workaround](https://codepen.io/luckylooke11/pen/YxwERL) Thanks

**Comment by luckylooke** [comment]
Fixed in new version 4.4.5 ;) Now it works as expected [see here](https://codepen.io/luckylooke11/pen/JyGqWq?editors=1010)
