### ISSUE TITLE
Docs are not working

### ISSUE THREAD

**Issue by orlandovallejos** [luckylooke/dragular#157]
http://luckylooke.github.io/dragular/
It's not working

I tried to fix this problem with this GitHub doc:
https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

But I couldn't find the problem, so I think it's something that the owner of the repository can fix.

**Comment by luckylooke** [comment]
Yes I have problems to make gulp task to work again. There is one npm package used, gulp-gh-pages. It was working a long time, I dont know what is the problem now.. :/ I will try some ideas with it. I hope I could make it work, if not I will try to replace it with some custom gulp task, or find another gulp-gh-pages alternative.

**Comment by luckylooke** [comment]
issue:
```
'deploy:docs' errored after 2.84 s
[21:15:55] Error in plugin 'gulp-gh-pages'
Message:
    Command failed: git rm -r .
error: the following file has local modifications:
    src/examples/partials/partial-home.html
(use --cached to keep the file, or -f to force removal)

Details:
    killed: false
    code: 1
    signal: null
    cmd: git rm -r .
```

**Comment by luckylooke** [comment]
I cannot find command `git rm -r .` where is it taken from.. and I have no local modification before task is started. So the modifications are created by the task it self..

**Comment by luckylooke** [comment]
Finally! I have fixed this by removing `.publish` directory and running command again. It is folder with temporary files which gulp-gh-pages uses, so there was something broken inside. Now it works again 🎉

**Comment by orlandovallejos** [comment]
Great! You're awesome!
