### ISSUE TITLE
How to get target model parent structure

### ISSUE THREAD

**Issue by orlandovallejos** [luckylooke/dragular#158]
Hello LuckyLooke/team!

I want to ask you something related to a recent bug you fixed #154 

In that case, we only drop elements with no models related, but what if we need the models to call an API or do some action?

Here an example: 
![Eg](https://d26dzxoao6i3hh.cloudfront.net/items/0P0q3D3P2j2x350V3T3F/Screen%20recording%202017-08-01%20at%2009.16.37%20PM.gif?v=5dd7aa06)
I wanted to drop an X-men into a category on the left, but when the drop event is executed I have those arrays modified and I don't have the items. Moreover, I got a new "category" on the left side (it's empty, but it's there).

These are the models (source and target):
![Models](https://d26dzxoao6i3hh.cloudfront.net/items/0n2R1o3S182h172Q361T/%5B98d01d1a96cc65c4de2023184b7d845c%5D_Image%25202017-08-01%2520at%25209.21.08%2520PM.png?v=2809a827)

As you can see, an X men was dropped into a category, and now he **IS** a category.

After some time reading the code I noticed that their parent is not being calculated correctly... just take a look at the same example, but not with the first elements of the lists:

![indexes problem](https://d26dzxoao6i3hh.cloudfront.net/items/1Z2P3l0q0D3b0c1l130J/Screen%20recording%202017-08-01%20at%2009.31.10%20PM.gif?v=6ac3e6cd)

And these are the models:
![Models](https://d26dzxoao6i3hh.cloudfront.net/items/3W0w2r1F3e0Q3L2U2m41/%5Bc75830896c8390e20f066dcb620b5790%5D_Image%25202017-08-01%2520at%25209.32.58%2520PM.png?v=e4d340db)

However, no mutant is removed from the array and they are not added to the category array, but in this case the indexes are correct. (Just see that Tony Hawk is being added back to the people array).

I don't know if maybe I'm not using this component correctly, or there's a problem, either way I tried to solve it but I couldn't.
Any help would be appreciated. 😃 

In this [commit](https://github.com/orlandovallejos/dragular/commit/6e011328f60b8003727569aae46310684847c93b) I created my tests, but I also created a [codepen](https://codepen.io/orlandovallejos/pen/qXZYVo?editors=1010).

**Comment by luckylooke** [comment]
I think I am lost :D Could you please as simple as possible tell me the use case? What exactly you want to happen when item from people is dropped into item menu? It seems to me that it can be done much easier but maybe I am missing something. 🤔

**Comment by orlandovallejos** [comment]
Well, I have 2 controllers, and in the first one I have an array of containers (this is dynamic), and in the second controller, I have a fixed container with draggable items.

I want to drag those items to the dynamic containers, and after that, perform some action with the item AND container, for example, call an API with both IDs (item and container).

I made some changes to the drop function, and now I get the dropped item:
`shared.skipDroppedElemFromTarget` This is a property I added is to avoid the adding of the dropped element into the target model.

I think that the main problem I have is that I need to know the container model (in my example, a specific category, for example, human, mutant, etc).

![Model](https://d26dzxoao6i3hh.cloudfront.net/items/041d0H063D0C3R2n2o3H/Screen%20recording%202017-08-02%20at%2009.10.41%20PM.gif?v=41af688a)

My changes to return the correct dragged model item:
![Change](https://d26dzxoao6i3hh.cloudfront.net/items/2N1i3k0y1a071B1d2135/%5Bec38d73b9c0b219ed7a53e574858e5b4%5D_Image%25202017-08-02%2520at%25209.13.07%2520PM.png?v=d08b7602)

But I still need the container model

I hope now it's a little bit clearer 
Thanks for your help

You can see those changes in this [commit](https://github.com/orlandovallejos/dragular/commit/c05bcb717db4848febc5b017f9c9ae0daf9e0512)

**Comment by orlandovallejos** [comment]
Hello LuckyLooke! 👋 

I wanted to tell you that I got working what I want,... but It's not well designed sadly

Here is the codepen: [https://codepen.io/orlandovallejos/pen/MvjdOp?editors=0010](https://codepen.io/orlandovallejos/pen/MvjdOp?editors=0010)

For my solution to work, I created a service that handles the models.
![image](https://user-images.githubusercontent.com/18174459/28940015-9cc27736-7869-11e7-81b7-9338fc7e3315.png)

But this is what I have to do to get the models from the "dragulardrop" event parameters:
![image](https://user-images.githubusercontent.com/18174459/28940078-dbebfaae-7869-11e7-9994-03adc9894c98.png)

where "scope()" is the scope of the ngRepeat item, and "item" is the name of the iteration in the view:

![image](https://user-images.githubusercontent.com/18174459/28940134-0d313eb2-786a-11e7-8876-0b670ab8de11.png)

And as you can see, the other ngRepeat item is called "p", and this is how I get it:
![image](https://user-images.githubusercontent.com/18174459/28940184-3707b932-786a-11e7-8302-fce1f3a935e7.png)

This is the workaround I found, but I believe we can come up with a better solution.

Have a great day! 😄

**Comment by luckylooke** [comment]
Yes you need another solution, because you cannot use `angular.element(el).scope()` in produciton.. it is working just in debug mode of angular. [see docs](https://docs.angularjs.org/api/ng/function/angular.element#methods)

Here is the problem:
`containersModel: [$scope.menuItems],`
`containersModel` must be array of arrays.. where each child array represents container.. this array is used for pushing dropped items

Another problem is that your menu containers does not show dropped items, but have one child (title), so the dropping index is always 1.. first time it will try to add at index 1 it will result in adding at position 0, all other it will add at index 1.. I dont know why exactly but it does not matter.

This is the codepen with fixes.. but it is not good implementation at all: https://codepen.io/luckylooke11/pen/prRgeQ?editors=0010

You should really tell me the use case, unless I cannot help you.. from code I thing that use case is:
1. person from people list is dropped into category
2. person dropped into category will disappear from people list
3. API is called with info from dropped person and category it was dropped in

If this is the case, confirm me, and I will show you much easier implementation then. ;)

Btw.. this condition is weird `if(people && person && categories, category) {` because there is comma operator it means that only last item is returned to if statement, so it is equivalent to `if(category) {`

**Comment by orlandovallejos** [comment]
Hi LuckyLooke! Thanks for the answer! 😃 

This is exactly what I need to do:
1. person from people list is dropped into category
2. person dropped into category will disappear from people list
3. API is called with info from dropped person and category it was dropped in

What you have in mind?

**Comment by luckylooke** [comment]
I leave this issue open until I make a release.. but [here is solution](https://codepen.io/luckylooke11/pen/zdwqvY) which I had in my mind. But there was a bug I had to fix. It is now in dev branch.. I will make new release soon, and I will notify you here so you can use this solution if you wish ;)

**Comment by luckylooke** [comment]
I have just released v4.4.6 with the fix included. Thanks for cooperation and happy coding ;)

**Comment by orlandovallejos** [comment]
Thanks a lot to you!
This will help me a lot! and I'm sure it'll help others like me!

Thanks for this amazing component!

That comma you mentioned in my code, that was a mistake, I wanted to add an AND (&&), I don't know why I wrote a comma.

Thanks for everything!
