### ISSUE TITLE
Preserve ng-click events

### ISSUE THREAD

**Issue by zsiswick** [luckylooke/dragular#16]
I have a use case where I'd like to preserve the ng-click event on a draggable container, however Dragular seems to disable this unless the element is an anchor or a button. This doesn't satisfy my use case because I want to be able to click anywhere on the element to trigger the ng-click event, and allow the user to drag from anywhere inside the element as well. Any suggestions?

<img width="305" alt="screen shot 2015-07-24 at 8 33 56 am" src="https://cloud.githubusercontent.com/assets/7780183/8874420/cc519eec-31de-11e5-8b4e-9f0fb0cf0d2c.png">

**Comment by luckylooke** [comment]
Yes I can put something to distinguish between click and drag, maybe something like [this](http://stackoverflow.com/a/6042235/861615). If you need it soon, you can PR ;)

**Comment by Astray-git** [comment]
Hmm have you tried the `delay` option? dragula example: http://bevacqua.github.io/dragula/#single2

**Comment by luckylooke** [comment]
@Astray-git is right, it is solved by delay option, I have tested it, see fiddle [here](http://jsfiddle.net/luckylooke/afv234uh/2/).

**Comment by jameswyse** [comment]
Delay is likely what you're looking for, but there's also the `invalid` option from dragula (it looks like it's implemented here, but not documented)


## `options.invalid`

You can provide an invalid method with a `(el, target)` signature. This method should return `true` for elements that shouldn't trigger a drag. Here's the default implementation, which prevents drags originating from anchor elements and buttons.

```javascript
function invalidTarget (el) {
  return el.tagName === 'A' || el.tagName === 'BUTTON';
}
```

Note that invalid will be invoked on the DOM element that was clicked and every parent up to immediate children of a drake container.

**Comment by zsiswick** [comment]
Using the delay property has resolved the problem I was having, I can now preserve ng-click events on draggable elements! Thanks very much for the support and code examples.
