### ISSUE TITLE
Dragular disable div's properties 

### ISSUE THREAD

**Issue by Anacarla64** [luckylooke/dragular#160]
Hi. I'm with a doubt:
I have this object
$scope.items : [{
     visible:true,
     groups:[{
            visible:true,
           subgroups:[{
               field:'AAA',
               type:'text'
           }]
     }]
}],
and I'm doing this in my html
//html code
<div ng-repeat="item in items" ng-init="itemI = $index">
    <div ng-repeat="groupItems in item.groups" ng-init="groupI = $index">
        <div id="dragAreaFields">
            <div ng-repeat="groupItems in groupItems.subgroup" ng-init="initDragularService(itemI, groupI)">
            </div>
        </div>

    </div>
</div>

//my controller function = 
$scope.initDragularService = function(_indexI, _indexG)
 var dragArea = document.querySelector('#dragAreaFields' + _indexG);
 dragularService([dragArea], {
    containersModel: [$scope.items[_indexI].groups[_indexI].subgroup,
    copy: true,
    boundingBox:true,
    accepts:false,
    isContainer: function isContainer (el) {
        return el.id === 'dragArea';
    },
    isContainerModel: function getModel (){
        return $scope.columns;
    }
});

At my drop area I put this code:

<div ng-repeat="column in columns">
    <input ng-model="test"> // issue here
</div>

When I'm trying to insert any value to this input text, it seems to be disabled and I can't edit or put something to bind inside the input text to make it work.

**Comment by luckylooke** [comment]
Please reproduce the problem somewhere I can examine the code..for example you can fork [this codepen](https://codepen.io/luckylooke/pen/pPmeWY)

And then describe the steps to reproduce the problem. Like:
1. drag second item from column B to column C
2. click on input in third item of column A
3. .. whatever else...
4. Expecting input to be enabled

Something like that.. thanks ;)
