### ISSUE TITLE
Cannot read property 'parentNode' of null

### ISSUE THREAD

**Issue by contactsandygo** [luckylooke/dragular#162]
I am exploring dragular for drag and drop windows with iframes rather than small simple divs containing texts. Intermittently source element is getting dropped at target but due following exception in code drop event does not fire hence information regarding drag drop get lost.

Uncaught TypeError: Cannot read property 'parentNode' of null
    at getParent (dragular.js:1501)
    at cancel (dragular.js:974)
    at HTMLHtmlElement.release (dragular.js:1021)

Can you suggest way to avoid this exception or if such exception occurs then element moves back to original position.

I have created plunker to explain the problem with these options

   dragularService('.containerVertical',{				 
				  direction: 'vertical',              // Y axis is considered when determining where an element would be dropped
				  revertOnSpill: true,               // item returns to original place
				  removeOnSpill: false                // item will be removed if not placed into valid target				 
			});   
     
https://plnkr.co/edit/VhvHsYSXFzWGGCWjFrjg

Thanks looking forward

**Comment by luckylooke** [comment]
Hi.. iframes are not supported, as you can see if you release drag over iframe the dragular lib did not catch the event. However.. I have tested your plunker and did not get the error.. I am on Mac OS Sierra with latest chrome. Could you tell me exact steps to get the error? Thanks

**Comment by contactsandygo** [comment]
Most of the time error will come when drag happens from bottom to top

for example  moving 5 or 6th element directly to 1st spot that time this exception comes.I agree that iframes is kind of challenging environment for drag drop but when  tried removing iframes and just with plain html this exception comes when we drag bottom items and move towards top. I guess it could relate to container size. If I use small rectangular container then there is less chance of this exception but as the size of dragable container increases exception becomes often particularly when drag action is from bottom to top vertically.

I have updated plunker by removing iframes also attaching screen cast

![output](https://user-images.githubusercontent.com/31977079/30495804-61b74dd2-9a1b-11e7-9658-2eb321f5a7df.gif)


Regards
San

**Comment by luckylooke** [comment]
I happy you managed to fix the problem, even I do not understand how moving controller from body to parent div can influence dragular.. it really interests me.. maybe it is just windows related, because I was moving controler definition around and error did not happened. But I have put too much energy into this, I need it for other projects.. so I leaving this how it is... I hope it will be OK for community. Thanks for your contribution and happy coding ;)
