### ISSUE TITLE
drag and drop not working correctly with list pagination?

### ISSUE THREAD

**Issue by rahi-rajeev** [luckylooke/dragular#164]
ng-repeat="list in prdData.specslist | filter:prdData.query | startFrom:prdData.currentPage*prdData.pageSize | limitTo:prdData.pageSize
i have create pagination of li

**Comment by luckylooke** [comment]
please reproduce the example.. I will solve it then.. thanks 
You can use [this pen](https://codepen.io/luckylooke/pen/pPmeWY) as starting point.

**Comment by rahi-rajeev** [comment]
hi  luckylooke,
please see below link
https://codepen.io/rahi-rajeev/pen/dVNede
my problem is that when page change then going to drag this page item then its drag  previous page same index value.
please resolve 
![a pen by rajeev rahi](https://user-images.githubusercontent.com/15867058/30845080-60b59e74-a2af-11e7-93e6-fadb60d346ca.png)

**Comment by luckylooke** [comment]
Thanks for reproduction, I will look at it soon, but no sooner then during this weekend. Thanks for understanding.

**Comment by luckylooke** [comment]
I does not have much time, but I have reviewed your code and have seen that you are using filters on model, so you need to help dragular providing same set of items in model, as are provided to ng-repeat. You can see example [here](http://luckylooke.github.io/dragular/#/docs/exampleNgRepeatFilteredWithModel). I will try to find time for helping you implement this into your case, but I cannot promise you anything, sorry.. I am trying to do everything, but there is limited time every day.

**Comment by luckylooke** [comment]
closing as inactive..
