### ISSUE TITLE
Drop not fired on tablet

### ISSUE THREAD

**Issue by albpara** [luckylooke/dragular#167]
Hi all,

I am doing some tests with the library and for some requirements, I have to use a "ugly" way to include this lib into my project, bust basically I created both service and directive into my folder structure and everything works fine... but only in browser.

When I use a tablet for testing purposes, the drop event is not fired not release method is never called, the cloned object stays on the last position I placed it, the original elements remains faded... and the drop is never executed... but if I try to drag the element again, the drop if correctly executed.

Any clue about my problem?

**Comment by albpara** [comment]
My logic is as simple as this:

```
.container(dragular='vm.options' dragular-model='vm.items')
  .item(ng-repeat='item in vm.items')
    div {{::item.name}}
```

**Comment by luckylooke** [comment]
I have no much time for this now (paid projects delays), please reproduce the problem at least so I can quick review it, maybe it is something I can solve really fast for you. Here is the [pen](https://codepen.io/luckylooke/pen/pPmeWY) you can use as starting point of your reproduction. Thanks for understanding.

**Comment by albpara** [comment]
Don't worry you don't need to excuse yourself!

I don't know what is going wrong, I tried on the same environment with a more simple setup and it works... I have to say that I tried this only on the browser tablet simulator from dev tools, tomorrow I will try a real tablet just to make sure that the error is present.

**Comment by albpara** [comment]
Damn,

I found the issue.

I am showing something like a item selector on a full screen overlay, if the overlay is clicked outside the selector, the overlay is dismissed, for that reason, I've created an stop propagation directive just to make sure that a click on the selector is not propagated

```
<div class='overlay' ng-click='hideShield()'>
  <div class='selector' stop-prpagation>
    <div class='inner' dragular='vm.options' dragular-model='vm.items'>
      <div class='item ng-repeat='item in vm.items'>
        <div ng-click='goToItem()'> {{::item.name}} </div>
      </div>
    </div>
  </div>
</div>
```

**Comment by luckylooke** [comment]
I am glad that you have found the problem. There is a lot of strange things in multiplatform development, we are now making projects in ionic2+ and sometimes it is like hunting witches, I may test on 5 devices and code is perfectly fine, then someone came with the sixth and tell me that it just does not work.. ;)
