### ISSUE TITLE
$element can't be injected as part of route change

### ISSUE THREAD

**Issue by cartwrightp** [luckylooke/dragular#2]
Hi there, 
Great work getting this going. The examples you show use ng-controller defined statically on the page. When used this way angular seems to have no trouble injecting in the $element dependency.

However when the controller is instantiated using angular route and associated with a partial view (like below) then the $element service just seems completely not injectable by angular. I suspect it isn't ready or available at the time the route change is being done. 

      $routeProvider.
          when('/Calculator', {
              templateUrl: uriUtility.getAbsoluteUri('PartialViews/Calculator.html'),
              controller: 'calcEngineController'
          }).

Do you have any ideas to get around this?

**Comment by luckylooke** [comment]
Could you provide live demo of problem please? So I can investigate a bit. Jsfiddle, codepen, jsbin, link to page whatever. Thanks

**Comment by cartwrightp** [comment]
Hi, 
I've created this. http://jsfiddle.net/3boccdu6/3/
When it first loads you can drag around Item1.,Item5 easily using dragular.

When you click on the route change link, the same idea is being tried but you will see it wont work. If you look for JS errors you will see there is an injector error complaining about $elementProvider. As mentioned I think its because the route is possibly still changing and the DOM may not even be ready yet for the partial view, so angular may not have an $element service available.

When I first tried to get this working I thought the $element service was quite critical to what Dragular needed which is why I raised this issue, then I saw in your documentation that it only needs an array of selectors which can obviously be obtained by any means. So for now I am just using another approach that doesn't rely on the $element service at all and that's OK.

I'm wondering if you created a wrapper directive to call your dragular factory/service you could wrap it all up without needing access to the controller. Callback functions could be defined that could call stuff back on the controller if required. Dragular options could be fed in via attributes on the directive, and the directive itself wouldn't run until the DOM was ready. 

Something like this maybe

<div dragular="{ removeOnSpill: true }">
<div>Drag me</div>
<div>And me</div>
</div>

In my situation the number of draggable elements are being controlled by an ng-repeat (so the user can add more) and I'm finding that new elements are not draggable (that's obvious because the dragularService doesn't know about the new ones). By trying to re-execute the dragularService again, I am having some problems where everything gets broken. I can raise this as another issue, or maybe discuss with you.

**Comment by luckylooke** [comment]
Thanks.. I will look at it soon.

**Comment by luckylooke** [comment]
Ok, there is already dragular directive I will highlight it in readme/usage soon. For now it just accepts name of the $scope property where settings are located, but I will improve it to accept JSON.

I will surely look at adding and removing elements when used with ng-repeat and will bring some solution. Please raise new issue for that, not to mix it here.

Thanks for using dragular ;)

**Comment by luckylooke** [comment]
NOTE: service accepts DOM element, or Array of DOM elements or Array-like object with DOM elements such as jqLite object or jQuery object. Selectors are not supported right now, because jqLite doesnt suport it either. BUT I can add support for selectors via querySelectorAll or if jQuery is loaded. Its good idea.

**Comment by luckylooke** [comment]
There was a typo in commit message (53c5caf).. its closing 3 not 2
