### ISSUE TITLE
Deploy:docs config bug (@alferov)

### ISSUE THREAD

**Issue by luckylooke** [luckylooke/dragular#27]
Hi @alferov!
I have fixed landing page for docs in exampleRouter.js, but file is loading from home/alferov/www/dragular, I think it is just matter of config, could you fix it please? Thanks ;)

**Comment by alferov** [comment]
Hey, could you provide more information regarding this issue? Logs? I just checked out the source and I didn't find any path matching this. Have you tried to rebuild source? I disabled absolute paths several days ago

**Comment by luckylooke** [comment]
Yes I have rebuilded.. open docs page with chrome console and go to sources
tabs you will see the path there. I can send you screenshot later.

**Comment by alferov** [comment]
Oh, found it

**Comment by luckylooke** [comment]
I have deployed:docs after build:docs and still same issue.. :/ exampleRouter.js is not from my files but from yours.. :disappointed:

**Comment by luckylooke** [comment]
I have found the problem, I have made changes without running watch task, so after build changes were applied only to minified files not to unminified. So I have turned dev task on and off to apply changes also there, and now it is correct ;)

**Comment by alferov** [comment]
Hey, let's build non-minified version too in that case?
Do you have any updates regarding the following issue?
> I have deployed:docs after build:docs and still same issue.. :/ exampleRouter.js is not from my files but from yours

**Comment by luckylooke** [comment]
I think it would be good to have just one build for all files minified and unminified. For 99% cases I touch both examples and library codes at once.

**Comment by alferov** [comment]
:ok_hand:
