### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by rbatllet** [luckylooke/dragular#30]
When I install dragular via bower:  
$ bower install dragular -save

A warning is displayed: 
bower mismatch      Version declared in the json (2.0.1) is different than the resolved one (2.1.0)

**Comment by jameswyse** [comment]
Looks like the `bower.json` and `package.json` files weren't updated with the last release.

@luckylooke do you use `npm run deployment`? Maybe that's another thing to add to gulp :tropical_drink:

**Comment by jameswyse** [comment]
@rbatllet If bower refuses to install you can try using `bower install dragular --save --force-latest` in the meantime :)

**Comment by rbatllet** [comment]
Dagular has been installed correctly but it shows this "warning" about the version

**Comment by luckylooke** [comment]
@jameswyse yes, I have had some problems with releases, I will fix it soon in next release ;)
@alferov could you please make task for deployment?

**Comment by luckylooke** [comment]
Should be fixed now..

**Comment by alferov** [comment]
We can use [gulp-bump](https://github.com/stevelacy/gulp-bump) for automated updates. What do you think, guys?

**Comment by luckylooke** [comment]
@alferov I think it would be better than editing manualy.. I almost every time forgot something in process of release... :disappointed:

**Comment by alferov** [comment]
Yeah, the same here :sweat_smile: 
Let me test it on my local repo first.
