### ISSUE TITLE
Official angular-dragula

### ISSUE THREAD

**Issue by luckylooke** [luckylooke/dragular#33]
Hi guys.. I am really considering to move our effort to [official angular-dragula](https://github.com/bevacqua/angular-dragula). I could manage to make first merge of our code base with theirs. What is you opinion @alferov @jameswyse?

**Comment by alferov** [comment]
:+1:
It's a good idea.
Have you reached out to the author?

**Comment by luckylooke** [comment]
Yes.. author is same as for original dragula.. I was invited to
contribute.. I will look at it in detail soon. But I hasitate because I
like gulp workflow more than their ugly unformated npm tasks same is for
demo page. Also he will make decisions about what to merge... :/ And I know
he refuse much new features because he wants to keep code small. But I was
intended to use dragular in huge frontend app where are lots of drag n drop
usecases. So I wanted to have only one dnd library instead of three I have
in the project now.

**Comment by alferov** [comment]
>  But I was intended to use dragular in huge frontend app

The same here

> he refuse much new features because he wants to keep code small

And new features should be implemented in the original dragula library first?

**Comment by luckylooke** [comment]
No.. but before I started dragular I was trying to contrib dragula. Also
when I watch issues in dragula he seems not to be forward to new
functionality.

**Comment by luckylooke** [comment]
For now, I will be contributing to both.. with dragular higher priority. :dancers:

**Comment by alferov** [comment]
That's awesome :+1:
