### ISSUE TITLE
cdn for production, locals for dev

### ISSUE THREAD

**Issue by luckylooke** [luckylooke/dragular#36]
Hi, @alferov, I'm on business trip now and I have very slow internet connection, which really slow downs development workflow loop due to CDN (bootstrap.min.css). Do you know some easy trick to switch CDNs to local sources in development and keep CDNs in production? :)

**Comment by alferov** [comment]
Hi, I guess [gulp-inject](https://www.npmjs.com/package/gulp-inject) + bower might be helpful. Every time when app runs in dev mode, `gulp-inject` takes index.html, parses, and injects local bower dependencies. I'm not sure about second part with wiring CDN dependencies. It would be perfect if that plugin could accept plain objects. Let me see what I can do with that. 
And we also need to be sure that we run `build:docs` task before `deploy:docs`.

**Comment by luckylooke** [comment]
Ok, please look at it.. we can use cdn also for angular than. ;)
