### ISSUE TITLE
Need little help from someone stackoverflow rank >1500

### ISSUE THREAD

**Issue by luckylooke** [luckylooke/dragular#38]
I need someone to create new TAG "dragular" on stackoverflow.com, so I can be notified about questions related to dragular. Only users ranked > 500 can create new tag. Thanks

**Comment by evenfrost** [comment]
Voted on some of your answers, so now you must have enough reputation to do this. Dragular deserves its own tag! :+1:

**Comment by luckylooke** [comment]
The reputation raised for a while but dropped again because the system detected your intentions.
![screenshot_2](https://cloud.githubusercontent.com/assets/3660030/12118820/c68d2064-b3c8-11e5-8d59-cd0140c17423.png)
I am bit surprised, but anyway they raised the level to 1500 meanwhile, so now I need to wait for achieving such level normally or have found someone who has already such level.
![screenshot_1](https://cloud.githubusercontent.com/assets/3660030/12118772/8fccf806-b3c8-11e5-8a1c-bb32b1bb51d3.png)
Thank you anyway for your attempt ;)

**Comment by ipavlic** [comment]
Created the tag.

**Comment by luckylooke** [comment]
Perfect.. thank you very much :)
Dňa 5.7.2016 12:18 používateľ "Ilija Pavlic" <notifications@github.com>
napísal:
