### ISSUE TITLE
Allow moving div in same container when copy: true

### ISSUE THREAD

**Issue by beatfreaker** [luckylooke/dragular#39]
Right now there is no option to allow to move a div in same container when `copy: true` is present in `option`.

check this [PR](https://github.com/bevacqua/dragula/pull/203) created for [dragula](http://bevacqua.github.io/dragula/)

**Comment by luckylooke** [comment]
Yes I was about implementing it. I just didnt have time. It will be implemented soon ;)

**Comment by luckylooke** [comment]
Should be solved by new release ;)
