### ISSUE TITLE
Dragular directive and events.

### ISSUE THREAD

**Issue by billxinli** [luckylooke/dragular#42]
Is it possible to register events with the use of the directive?

**Comment by billxinli** [comment]
Read the code, yes, the `gh-pages` have the wrong event names listed. They should have been prefixed with `dragular`. Looking at the example source, not sure why the following was commented out.
```
// $scope.$on('dragularcloned', myFn('cloned'));
// $scope.$on('dragulardrag', myFn('drag'));
// $scope.$on('dragularcancel', myFn('cancel'));
// $scope.$on('dragulardrop', myFn('drop'));
// $scope.$on('dragularremove', myFn('remove'));
// $scope.$on('dragulardragend', myFn('dragend'));
// $scope.$on('dragularshadow', myFn('shadow'));

// function myFn(eventName) {
//   return function() {
//     console.log(eventName, arguments);
//   };
// }
```

In my project I did the following to figure out what everything did:
```
_.forEach(['dragularcloned', 'dragulardrag', 'dragularrelease', 'dragularcancel', 'dragulardrop', 
           'dragularremove', 'dragularout', 'dragularover', 'dragulardragend', 'dragularshadow'], 
            function (event) {
              $scope.$on(event, function (e) {
                console.log(event, arguments)
                e.stopPropagation()
              })
            })
```

**Comment by luckylooke** [comment]
I am sorry that it caused you troubles and waste your time, mostly I am doing it in late evenings so I had to forgot updating that info. Now fixed. Thanks for your report :+1:

**Comment by billxinli** [comment]
Oh no worries. It was a good exercise for me regardless. Thank you for your contribution to this library!

**Comment by luckylooke** [comment]
Ok, I will do my best to maintain and develop it correctly. It is exercise for me every time. I am just getting experience with all about open projects. Any help appreciated ;)
