### ISSUE TITLE
Changing model values when dragging

### ISSUE THREAD

**Issue by fisuser** [luckylooke/dragular#43]
Hello Lucklooke, thanks for this wonderful project. 

I have a question regarding the usage of this. I implemented drag and drop with this project in angular. My question is :- I am using a list of objects as my model, which I set in the div using ng-repeat. When I drag an item o another div, is it possible to change/modify some property of the object that I dragged ?

I tried ways to get the model of the moving object, but failed. Hope someone have found a solution for this.

**Comment by luckylooke** [comment]
Model of dragged element can be accessed via service ```dragularService.shared.sourceModel[dragularService.shared.initialIndex]```. I know it is not very polished way, but it should work ;)
