### ISSUE TITLE
Sometime not able to select a checkbox under ng-repeat

### ISSUE THREAD

**Issue by vmrathod** [luckylooke/dragular#44]
I have ng-repeat in container and under ng-repeat I have checkbox under div.

But sometime I am not able to select a checkbox, dragular only fire the event for mousedown and drag.

Any idea?

Thanks

**Comment by luckylooke** [comment]
I think that problem would be similar to [this one](https://github.com/bevacqua/dragula/issues/232). So it will be solved after merging dragula changes into dragular. Maybe this weekend.

**Comment by luckylooke** [comment]
I was just looking at the [PR fixing that issue](https://github.com/bevacqua/dragula/pull/235/files) in dragula and it is pretty simple. You could try it in your enviroment, if it successfuly solve your problem then you can PR here.

**Comment by vmrathod** [comment]
Hi,

It's working.

I used e.target.type=='checkbox'.

Thanks
Vishal Rathod

**Comment by luckylooke** [comment]
Ok you can PR then.. or I will in couple of days..

**Comment by luckylooke** [comment]
Should be solved by new release ;)

**Comment by vmrathod** [comment]
Hi,
I haven't try new version.

Definitely I would like to try it.

Thank very much for update. :)

Thanks
Vishal Rathod
