### ISSUE TITLE
Cannot sync with model when the model is filled by a promise

### ISSUE THREAD

**Issue by Hyzual** [luckylooke/dragular#46]
Hi !

I'm having an issue when using dragular v3.2.0. I have a model array, say ` test_model` that is filled asynchronously using a promise ($q). I want each item of this array to be draggable with dragular with the option `containersModel: test_model` , but it seems that in this configuration every time I drop an item, it disappears and the javascript model is not updated.

Here is a plunker that shows the issue : http://plnkr.co/edit/ksLE1T7gVovoWrWnBwfp?p=preview

If you try to edit it, you'll notice that if ` test_model` is defined directly without using a promise, it works as expected.

I would very much like to see this issue resolved as it seems to be the only thing stopping us from replacing our current (slow) javascript drag'n'drop library with dragular.

Let me know if there is anything I can do to help.

**Comment by luckylooke** [comment]
Hi, thanks for using dragular, what you need is pushing new items into array you provided to dragular, it is matter of javascript language, that non-primitive values are using references. In your code you have changed reference to new array in deferred callback function, so dragular was binded to empty array you assigned to test_model property in the beginning.  I have edited your plunker, I think you will notice well whats going on ;) Here is [link](http://plnkr.co/edit/BGt1c4XBLzLqesg1zDWd?p=preview).

**Comment by aubm** [comment]
Hello ! I am facing the same problem right now. Unfortunately, containing the reference does not appear as a solution in my case.

I thought to the possibility of providing a callback function instead of an array. I could submit a push request if you think this is a solution that could do the trick.

**Comment by davinkevin** [comment]
+1 with this comment.

In Angular (1 and 2), we encourage the usage of immutability, and in our dev we can't keep the same reference all the time.

**Comment by luckylooke** [comment]
Reference is also kept in drake object for you, but anyway I will rethink this and come with better solution. But not sooner than next week. I dont have much time now.
