### ISSUE TITLE
How to re-initialize the dragularService? I keep running into error...

### ISSUE THREAD

**Issue by hughred22** [luckylooke/dragular#47]
So in my Angular App, I have 2 drag container. I use this format to set them up: 

         drakeObj = dragularService("#containerVideosDrag", {
		containersModel: admin.addedVideos,
		scope: $scope,
	});
         drakeObj = dragularService("#containerSlidersDrag", {
		containersModel: admin.addedSliders,
		scope: $scope,
	});

And the page need to load different elements inside the #containerVideosDrag and the #containerSlidersDrag container. So everything need to reset / re-initialize without a forced page refresh. I try to set 
drakeObj.destroy(); 
OR
drakeObj = {}
OR
drakeObj.containers.dragularCommon.splice(0, 2);
OR
drakeObj.containers.dragularCommon = [];

But none of it works. So when load new element from the server and new content into the #containerVideosDrag and the #containerSlidersDrag container and drag again, this error show up:

angular.js:12477 TypeError: Cannot read property 'null' of null
    at dragular.js:523
    at Scope.$eval (angular.js:15989)
    at $applyAsyncExpression (angular.js:16128)
    at flushApplyAsync (angular.js:16381)
    at Scope.$eval (angular.js:15989)
    at Scope.$apply (angular.js:16089)
    at angular.js:16392
    at completeOutstandingRequest (angular.js:5507)
    at angular.js:5784(anonymous function) @ angular.js:12477(anonymous function) @ angular.js:9246flushApplyAsync @ angular.js:16383Scope.$eval @ angular.js:15989Scope.$apply @ angular.js:16089(anonymous function) @ angular.js:16392completeOutstandingRequest @ angular.js:5507(anonymous function) @ angular.js:5784
dragular.js:582 Uncaught TypeError: Cannot read property 'parentElement' of null

Force refresh the page is the only way to reset dragularService now. Please help to clearly destroy all the  dragularService without page refresh so I can reuse drakeObj = dragularService(...

**Comment by luckylooke** [comment]
I am sorry I have somehow missed this issue.
You have several posibilities here, depends on what is your goal.
As I understand you just want to clear items from containers.
You can achieve this by setting your model array length to 0
```js
admin.addedVideos.length = 0;
``` 
You can also access model via drake this way
```js
drakeObj.containersCtx.dragularCommon[0].m.length = 0;
```
containers property keeps references to containers DOM objects
containersCtx keeps its contexts in two another members
m - for model
and
o - for options the container has been initiated with
dragularCommon is default namespace to keep containers separated from other namespaces

I hope it will help you ;)

**Comment by itprogrammer2** [comment]
This thread may be closed but I happen to came across this today and did not get the best solution so I think I have to comment for anyone who may need it in the future. The solution is this:

> dragularService.cleanEnviroment();

**Comment by SkalaSmrdi** [comment]
Hi, I operate with same problem. I have one container which is dynamically reinitialized with new array. For me works good when i keep reference for drake object and when new array comes only call drake.destroy() to clean drake object and reinit with dragularService. initDragular is called in watcher when source array (messages) is changed. Hope that it helps to someone.
Source code:
`var ddCont = elem.children().children(); `
`var drakeObj; `
`function initDragular() {`
`   if(drakeObj){`
`      drakeObj.destroy();`
`   }`
`   drakeObj = dragularService(ddCont[0], {`
`       moves: function (el, container, handle) { return handle.className === 'handle'; }`,
`       scope: scope,`
`       containersModel: scope.messengerSet.messages`
`  }); `
` }`
