### ISSUE TITLE
Doesn't work on ipad/touch devices

### ISSUE THREAD

**Issue by Anshx** [luckylooke/dragular#50]
It doesn't work on ipad or any kind of touch devices!

**Comment by luckylooke** [comment]
I have tested it on emulators, but I will retest in real touch device soon.

**Comment by luckylooke** [comment]
Should be fixed in new release, I have tested it on Samsung galaxy s4, please retest also with your device, thanks!

**Comment by Anshx** [comment]
I tested it on ipad and htc, it works fine now. Thanks!
