### ISSUE TITLE
Filtered Model not copied to target Model

### ISSUE THREAD

**Issue by Presta-Lab** [luckylooke/dragular#53]
Hi, thanks for your awesome adaptation of dragula to angular, I love it!

I'm trying to copy the data from a filtered ng-repeat model to a target model, but it doesn't works, only I have a copy of the ng-repeat node in the target zone, and the target model empty. I don't know if I'm doing something wrong or  I missing something in the docs.

Can you take a quick look to this simple example please?
http://plnkr.co/edit/78NX5QDpbMTklVzdAdap?p=preview

Best regards.

**Comment by luckylooke** [comment]
Your setup is good, I must solve some problems with filtered models, I realised the problem few days ago #48. Please give me few days to fix it ;)

**Comment by luckylooke** [comment]
Solved in DEV branch, for now just for Objects, but it will be for primitive values soon. There is new example in DEV brach called 'Filtered ngRepeat - with model'

**Comment by luckylooke** [comment]
Better explained, it will work also with primitive values unless there are no dupes of values ;)

**Comment by luckylooke** [comment]
I will keep it open until next release.

**Comment by luckylooke** [comment]
fixed in v3.4.0, @Presta-Lab thanks for contribution :+1:

**Comment by Presta-Lab** [comment]
Hi @luckylooke Thanks for your fixes!! I tested your new version 4.0 and about filtered ng-repeat don't works at all.

if I set get the resource model directly from query `$scope.apiElements = ApiResource.query();` works fine.

but if I set the model async don't work, and only copies the snapshot as before.
`        ApiResource.query(function(res) {
            $scope.apiElements = res;
        });`

Would be perfect if we can set the model from query async function, because we can sent more than one model from resource, as:

`        ApiResource.query(function(res) {
            $scope.dragModel1 = res.model1;
            $scope.dragModel2 = res.model2;
        });`

I updated the example in plunker: http://plnkr.co/edit/DtTEsrZQ3fpE7NsRgCbD?p=preview 

The first example have the issue where are set the vars in query function, you can comment the lines 22-25 and uncomment the line 20 to see that works fine.

May be I'm doing something wrong?

**Comment by Presta-Lab** [comment]
Finally I set all the dragular services in the query function and works fine!

Best regards.

**Comment by luckylooke** [comment]
Can you post me also updated (how you fixed it) version of your plunker? So
I can look at it if there is no space for improvement. Thanks

**Comment by Presta-Lab** [comment]
Yes, As finally I can send more data from the api rest, I think is better to set the dragular services when the data are received asyncronous.

I fixed here.

http://plnkr.co/edit/rHr9CH9OqdI2jUEuNhWQ?p=preview

**Comment by luckylooke** [comment]
Async should be working as well.. maybe $apply was missing there.
```
ApiResource.query(function(res) { 
$scope.apiElements = res; 
$scope.$apply(); // you need to inform angular that you made changes on model
});

**Comment by Presta-Lab** [comment]
Hey @luckylooke! Thanks for your support.

Don't work with $scope.$apply();

Only works with this way
`        // *** SET VARS AND DRAGULAR SERVICES WHEN DATA ARE READY ****
        MagicMailResource.query(function(res) {
            $scope.categories = res[0].categories;
            $scope.apiElements = res[0].elements;

            dragularService.cleanEnviroment();

            dragularService(dragZone, {
                //move only from left to right
                containersModel: $scope.apiElements,
                containersFilteredModel: $scope.filteredItems,
                copy: true,
                accepts: accepts
            });
    
            dragularService(dropZone, {
                //move only from left to right
                containersModel: $scope.emailElements,
                accepts: accepts
            });
        });`
