### ISSUE TITLE
Can't make it work on tablet

### ISSUE THREAD

**Issue by johnfumaster** [luckylooke/dragular#54]
Below is my set up. It works fine on desktop, but when I try the dragging on tablet mode, it doesn't do anything.  Is there something I need to do? 
```
<div ng-controller="testCtrl">
    <div class="test">
         <div class="drag">TEST</div>
    </div>
</div>
````

````
var app = angular.module('app', ['ngAnimate', 'ngTouch', 'infinite-scroll', 'ui.bootstrap', 'uiSlider','dragularModule']);

app.controller('testCtrl', function ($scope, dragularService, $timeout, $interval, $rootScope) {
    dragularService.cleanEnviroment();
    dragularService('.test', {
        scope: $scope
    });
});
````

**Comment by luckylooke** [comment]
Your setup looks good to me, scope option is optional, needed only if you want to listen to events. Please check the version you are running, I was fixing touch bugs in latest release 3.3.1.

**Comment by johnfumaster** [comment]
The version I'm using is version 3.3.1.

Maybe it works on a real touch device, I was only testing in chrome's
emulation mode.  I don't know as I never got around to testing it on a
touch device (didn't have one at hand).  So I ended up retrofitting what
you had for lockX, lockY, and boundingBox into angular-dragula.  Would be
great if I could swap it back to using dragular though.

Thanks for the work though.  It's really neat.

**Comment by luckylooke** [comment]
Have you tried [examples in docs](http://luckylooke.github.io/dragular/#/docs/exampleBasicWithModel) with your emulating setup?

I was testing it with real touch device and emulators too, and everything is working fine there.

If it doesnt work for you, please tell me what device are you emulating, so I can reproduce it. If examples works for you, and your code doesnt, please provide live version of your code, like codepen, jsfiddle, whatever I can access and investigate. Thanks
