### ISSUE TITLE
Drop items into a non-list container

### ISSUE THREAD

**Issue by letalumil** [luckylooke/dragular#55]
I need to drop items from a list into a non-list container without any shadow and sorting within the target container. It should work like [here](http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/nested). Just pick any element and drop it into the trashcan.
Is it possible to achieve this functionality with dragular?
Thanks!

**Comment by letalumil** [comment]
I just found [this thread](https://github.com/bevacqua/dragula/issues/222). But can't get the idea how to implement it yet.

**Comment by luckylooke** [comment]
Simplest way how to achieve this is taking "[isContainer](http://luckylooke.github.io/dragular/#/docs/exampleIsContainerWithModel)" example and adding new CSS rule ```div#cart div {
    display: none;
}```
It can be acheived with any drop area.
If you dont want to collect nondisplayed elements in trash, you can provide scope in options object on init and listen to dragulardrop event. In handler you can remove the element from DOM.

But in future I will build some better functionality to make this things better way ;) I've just got good idea how it should be made.

**Comment by luckylooke** [comment]
Or, another solution came to my mind. You can init trash drop area separately.
```
dragularService(trashElement, {
      scope: $scope
    });

$scope.$on('dragulardrop', function (event,item) {
  item.parentNode.removeChild(item);
});
```
