### ISSUE TITLE
commonjs syntax for webpack

### ISSUE THREAD

**Issue by blackendstudios** [luckylooke/dragular#58]
hi, your library is cool but at the time of importing it through webpack I got this message

WARNING in ./~/dragular/dist/dragular.min.js
Critical dependencies:
1:113-120 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/dragular/dist/dragular.min.js 1:113-120

maybe an index.js pointing to a simple clean concatenated file will be more confortable :)

like angular

**Comment by luckylooke** [comment]
Could you make PR for it please?

**Comment by blackendstudios** [comment]
can't create a pull request

![screenshot from 2016-01-24 10 40 44](https://cloud.githubusercontent.com/assets/4050205/12537184/f5480230-c286-11e5-8ad1-44421a276ad8.png)

**Comment by wezeolaky** [comment]
I dont know what is the problem, but please try this:
Create fork, push it there and the create pull request via github webpage, thanks ;)

**Comment by luckylooke** [comment]
@blackendstudios please PR to dev branch, thanks

**Comment by blackendstudios** [comment]
I can't, same message again and pointing to dev branh

**Comment by luckylooke** [comment]
@blackendstudios try to push into your fork and then create PR via github website, thanks

**Comment by blackendstudios** [comment]
done :) I just pointed out how the file will be more friendly to use with webpack, I think browserify isn't necessary for a small library

**Comment by luckylooke** [comment]
Browserify isn't necessary now, but I am planing to chunk the library to smaller parts in future, so I would like to keep it there.

**Comment by blackendstudios** [comment]
ok ok ok, that's pretty, as soon I can use it with no issues with webpack, is all good to me
