### ISSUE TITLE
options for different container is not possible?

### ISSUE THREAD

**Issue by codeyad** [luckylooke/dragular#6]
let me write an example, there are  2 containers (containerA, containerB), i want containerA with the "copy" option set to true so that this can just copy to containerB, but i want containerB to be set true in the "removeOnSpill" option so i can remove elements from this container, i have tried many ways but havent found a way to make this work, is there a way to do what i want or should i do a hack to do that?

**Comment by luckylooke** [comment]
```javascript
dragularService($('.containerA'), {
  nameSpace: 'sameDomain',
  copy: true
});
dragularService($('.containerB'), {
  nameSpace: 'sameDomain',
  removeOnSpill: true
});
```

**Comment by luckylooke** [comment]
It seems that this will not work in latest dragular. I have moved event handler from containers to document as original dragula did. But in such case like your it seems to have problems. I will investigate it more soon. Since then you can use the snipped I gave you but with dragular < 1.3.0!
