### ISSUE TITLE
tree structure

### ISSUE THREAD

**Issue by blackendstudios** [luckylooke/dragular#60]
hi, well, this is an opinion on what about a tree structure, I'll be great if dragular could have this kind of feature, I found an example but I think isn't friendly to use.

http://angular-ui-tree.github.io/angular-ui-tree/#/basic-example

maybe dragular can Improve that area.

also it lacks of 'controller aliasing', so there a bunch of $scopes round there

they implement this.scope = $scope

**Comment by luckylooke** [comment]
I think that it is possible to build ui-tree funcionality with todays dragular version, but I also believe that there is space for improvements. But for now I have priority to make codebase more maintanable, so I am refactoring it step by step and planing to devide it into smaller parts. Also test are planned.

**Comment by Hyzual** [comment]
Hi, just to let you know, we managed to build an application that uses a tree structure with dragular. In fact we previously used angular-ui-tree before switching to dragular (which has far better performance).

You can take a look at the code here: https://github.com/Enalean/tuleap/blob/master/plugins/agiledashboard/www/js/planning-v2/src/app/backlog-item/backlog-item-controller.js

The code is licensed under GPL v2 so you can maybe reuse it (depending on your license).
I don't think I have a public running instance to show you it works though :disappointed:.

We even went further than angular-ui-tree and allowed drag and dropping multiple elements at once or dropping a child item on a collapsed parent item.

**Comment by luckylooke** [comment]
Thats really cool info, I am looking forward trying it. I will go trough
your code to see what can I do to better support this use case. ;)

**Comment by kschwidder** [comment]
@Hyzual could you share more of the code. We are also hitting the stage to provide a tree structure of boards and are struggling with the drag and drop function. Any more details is highly appreciated. 
@luckylooke it would be awesome to have the nested tree structure available in dragular. A majority of apps do have hierarchies and needs for this

Thx for this great tools !

**Comment by luckylooke** [comment]
@kschwidder yes it would be awesome, but for now I am spending my free time in new DnD library with taking best parts of dragula and SOLID principles together. Building tree structures there will be easy. I am in testing/bugfixing phase on core there. I think it will be finished in few weeks.

**Comment by Hyzual** [comment]
@kschwidder
On my project, we only have to deal with 1 level deep trees: 

``` 
- draggable item
    - draggable child
    - draggable child
```

To implement this, we use an angular directive called "backlog-item", which always has a "backlog-item-details", which represents the "draggable item". It also has a list (using ng-repeat) of other "backlog-item-details") which represent the "draggable children".
Here it is in pseudo-code:

```html
<backlog-item>
  <backlog-item-details/>
  <ul ng-repeat="child in children">
    <backlog-item-details/>
  </ul>
</backlog-item>
```

The "backlog-item" directive has a controller attached, it deals with all the "draggable children" that are in it and that can be dropped elsewhere. What we use mainly is the event 'dragularDrop'. We use a callback, get the information we need and call a REST route to update.

For the detail of this code see [the controller](https://github.com/Enalean/tuleap/blob/master/plugins/agiledashboard/www/js/planning-v2/src/app/backlog-item/backlog-item-controller.js) and [the template](https://github.com/Enalean/tuleap/blob/master/plugins/agiledashboard/www/js/planning-v2/src/app/backlog-item/backlog-item.tpl.html).

I hope this helps !
