### ISSUE TITLE
copy option breaks model bindings

### ISSUE THREAD

**Issue by nowtvicebergteam** [luckylooke/dragular#61]
When using `options.copy`, the model is being copied via `angular.copy` (https://github.com/luckylooke/dragular/blob/master/src/dragularService.js#L532).

```js
        $rootScope.$applyAsync(function applyDrop() {
          if (target === shared.source) {
            shared.sourceModel.splice(dropIndex, 0, shared.sourceModel.splice(shared.initialIndex, 1)[0]);
          } else {
            shared.dropElmModel = shared.copy ? angular.copy(shared.sourceModel[shared.initialIndex]) : shared.sourceModel[shared.initialIndex];

            if (!shared.tempModel) {
              shared.targetModel = shared.targetCtx.m;
            } else {
              shared.targetModel = shared.tempModel;
```

Is this intentional or a known issue?

The problem is that this breaks scope binding. E.g. when editing the "original" model, the copied model (that has been dropped into a different container) is not being updated.

**Comment by luckylooke** [comment]
It is intentional.. in my use cases I didnt want copies to reference same object in model. But I can provide flag in options for setting the behavior for not cloning model. Like 'options.dontCopyModel = true'.

**Comment by nowtvicebergteam** [comment]
Awesome. Thanks!
