### ISSUE TITLE
Not usable from browserify

### ISSUE THREAD

**Issue by mzahor** [luckylooke/dragular#62]
Would be great to have a possibility to use it as a CommonJS module.

**Comment by luckylooke** [comment]
Please write me a bit more how would you like to use it? Code example would be the best. Thanks

**Comment by mzahor** [comment]
I have an app which I build with `browserify`. In my `main.js` I include libraries with `require`.
I want to require dragular like this:
```js
require('dragular');
```

**Comment by luckylooke** [comment]
I have done some changes, please try latest dev branch and test it in your enviroment, whether it fits your requirements. Thanks

**Comment by mzahor** [comment]
Still no luck:
```
  1 events.js:85
  2       throw er; // Unhandled 'error' event
  3             ^
  4 Error: Cannot find module './dragularModule' from
  5 '/opt/testproject/ui-angular/node_modules/dragular/dist'
  6     at
  7 /opt/testproject/ui-angular/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
  8     at load
  9 (/opt/testproject/ui-angular/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
 10     at onex
 11 (/opt/testproject/ui-angular/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
 12     at
 13 /opt/testproject/ui-angular/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
 14     at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by luckylooke** [comment]
Please could you make a live example (jsfiddle, codepen, jsbin...) so I can
test against it? Thank you

**Comment by mzahor** [comment]
Ok, I will try to create an example

**Comment by mzahor** [comment]
I've created a repo based on browserify/angular boilerplate and added dragular in the last commit. Please take a look.
git@github.com:mzahor/dragular-commonjs-test.git

**Comment by luckylooke** [comment]
Ok, thanks I will look at it soon.

**Comment by luckylooke** [comment]
I was trying to fight browserify, but I cannot make it work correctly. Are you able to do it please?

**Comment by mzahor** [comment]
@luckylooke Ok, I'll take a look during this weekend.

**Comment by luckylooke** [comment]
I am focusing on library code it self, so gulpfile, browserify and other workflow stuff was setuped by one of contributors @alferov. You are free to do whatever you consider as improvement. Thank you for your time spent on contributing here!

**Comment by alferov** [comment]
Hey guys, I'll take a look at it this weekend

**Comment by luckylooke** [comment]
Ok @alferov you do first shot, as it is coded by you, so it should be easier for you. If you will have problems to manage it, then @mzahor can try. Thank you guys for your effort.

**Comment by alferov** [comment]
I got it working:
https://github.com/alferov/dragular-commonjs-test
The thing is, I migrated to webpack. I spent about an hour playing with browserify settings last night, but   all attempts failed. So instead of trying to fix browserify I installed webpack (https://github.com/alferov/dragular/tree/webpack) and It worked.

I can finish the migration in a couple of days and make a PR.

**Comment by luckylooke** [comment]
Cool.. I am looking forward to get used to webpack.. I have heart a lot about it. ;)

**Comment by luckylooke** [comment]
@mzahor please retest with latest dev branch, should be done by @alferov with #66

**Comment by mzahor** [comment]
Still not working. I'm using this repo for testing: https://github.com/mzahor/dragular-commonjs-test

**Comment by alferov** [comment]
@mzahor Can you delete your `node_modules` folder and make a fresh install?

**Comment by mzahor** [comment]
@alferov Yes, after reinstalling node modules everything works good. Thanks a lot guys! Closing the issue.

**Comment by luckylooke** [comment]
@alferov and @mzahor thank you both for your contribution! :+1:
