### ISSUE TITLE
How to use drag and drop on mobile

### ISSUE THREAD

**Issue by caohothang** [luckylooke/dragular#63]
Can you support me ?

**Comment by luckylooke** [comment]
Of course.. describe your problem please.

**Comment by caohothang** [comment]
I using your library, it working nice in desktop but in mobile i can't drag and drop it.

This is my code

 var containerLeft = document.querySelector('#containerLeft'),
          containerRight = document.querySelector('#containerRight');

  function accepts(el, target, source) {
    if (source === containerLeft || source === target) {
      return true;
    }
  }

  dragularService([containerLeft], {
    scope: $scope,
    containersModel: [$scope.exercises],
    copy: true,
    //move only from left to right  
    accepts: accepts
  });

  dragularService([containerRight], {
    scope: $scope,
    containersModel: [$scope.plan.exercises],
    removeOnSpill: true,
    //move only from left to right  
    accepts: accepts
  });

  $scope.$on('dragulardrag', function(e, el) {
    e.stopPropagation();
    $(el).find('.fa-heart').hide();
  });
  $scope.$on('dragulardrop', function(e, el) {
    e.stopPropagation();
    // $('.fa-heart').show();
    $timeout(function() {
      $scope.updatePlan();
    }, 50);
  });

**Comment by luckylooke** [comment]
Your code works without problem on my android phone [here](http://jsfiddle.net/luckylooke/bLyts9uc/1/). So if you have any problems, try to reproduce it there and reopen issue. Thanks

**Comment by flick36** [comment]
What about this one:

http://codepen.io/jameswyse/pen/JdBPJd

its doesnt work in mobile in this one, i'm asking cause i cant make it work in my project either

**Comment by caohothang** [comment]
Yes, in my mobile it not working like flick46...

**Comment by luckylooke** [comment]
@flick36 and @caohothang, I have found the bug, it is because jQuery encapsulates events so it doesnt have `touches` property, which dragular use to detect correct touch. In jQuery events property `touches` is located in `event.originalEvent.touches`. I will fix it ASAP, thanks for your contribution ;)

**Comment by caohothang** [comment]
@luckylooke Thanks you
I will wait new update from you :+1:

**Comment by luckylooke** [comment]
jQuery enviroment fixes merged! ;)

**Comment by caohothang** [comment]
@luckylooke 
So i will pull new code from git and update to my library js, right?

**Comment by luckylooke** [comment]
If you are using npm or bower, you can update it via them. You dont need to do it manually. But if you are not using those tools you can just replace dragular.js or dragular.min.js. ;)
