### ISSUE TITLE
How I can disable Dragular?

### ISSUE THREAD

**Issue by Presta-Lab** [luckylooke/dragular#64]
I'm triyng to disable dragular with a chekbox with the aiming to modify the target content, but when the disable flag is on, the source and target drag still working but no drop. And on target model If I have more than one element, I can drop the elements only to the latest slot.

Is there any flag on dragularService for a safe disable?

You can see this example on: 

`         /*** SET VARS AND DRAGULAR SERVICES WHEN DATA ARE READY ****/

        MagicMailResource.query(function(res) {
            $scope.categories = res[0].categories;
            $scope.apiElements = res[0].elements;

            dragularService.cleanEnviroment();
            // Asignamos a esta etiqueta el comportamiento y origen de datos
            dragularService(dragZone, {
                //move only from left to right
                containersModel: $scope.apiElements,
                containersFilteredModel: $scope.filteredItems,
                copy: true,
                accepts: accepts
            });
    
            // Esta etiqueta asígna el modelo de datos vacío y la funcción de control
            dragularService(dropZone, {
                //move only from left to right
                containersModel: $scope.emailElements,
                accepts: accepts
            });
        });`

**Comment by luckylooke** [comment]
You can provide "moves" callback fn in options object.
```
dragularService(dragZone, {
          // moves only if dragular is enabled
           moves: function (el, container, handle) {
                 return $scope.dragularEnabled;
             },
            //move only from left to right
            containersModel: $scope.apiElements,
            containersFilteredModel: $scope.filteredItems,
            copy: true,
            accepts: accepts
        });
```

;)

**Comment by Presta-Lab** [comment]
Works Perfect! :)

Thank you so much @luckylooke!
