### ISSUE TITLE
Get a reference to drake when using the directive

### ISSUE THREAD

**Issue by Hyzual** [luckylooke/dragular#65]
Hi,

In our application we want to cancel drag and drop using the 'ESC' key. We made our own directive for that purpose but it forced us to change from using the dragular directive to the dragular service. We had to do this because the only way to get the drake object is through the dragular service. It causes other problems (dealing with init of the dragular service, etc).
We would like to have a way to get a hold of the drake created when using the dragular directive.
I don't think I'll have time to make a PR soon, anyway my first idea would be to add an isolate scope to the directive with a property or function returning the drake object reference that the directive would update.
Something like that: 

```javascript
scope: {
    drake: '=dragularDrake'
}
```

We could then attach it to the model:

```html
<ul dragular dragular-drake="vm.drake"></ul>
```

What do you think about it ?

**Comment by luckylooke** [comment]
I will be thinking about it during the weekend and let you know then. I dont like much the idea about new scope creation, it leads to conflicts to other directives or more complicated html structures. Maybe there is better solution, but I need a bit time to think about it. ;)

**Comment by luckylooke** [comment]
I have some idea, but I also have one important deadline on 3th of March, so I will start working on this feature after then, sorry.

**Comment by Hyzual** [comment]
No problem, I'm not in a hurry :)

**Comment by luckylooke** [comment]
Hi, deadline was moved to 20th of March, so now I have time, but I have also lots of postponed work since then. I have an idea of creating new attribute like ```dragular-oninit="wm.myCallbackFn"``` so you can provide callback function which will be executed with ```drake``` as first parameter and you can the do whatever you want with it. What do you think about that?

**Comment by Hyzual** [comment]
Hi, that looks good to me. This is exactly what we need. I suggest naming the attribute `dragular-on-init` (added dash for readability) but I'm okay with it as you described it.

**Comment by luckylooke** [comment]
Ok.. I will add it soon ;)

**Comment by luckylooke** [comment]
Added in dev branch.. will be merged to master later on next release.

**Comment by Hyzual** [comment]
Thanks a lot, I'll test it whenever I get the chance !

**Comment by Hyzual** [comment]
Hi, just wanted to let you know that the onInit option works great, it's really going to simplify our code. Thanks !

**Comment by phazei** [comment]
I'm using the onInit to get Drake, but I have a page with 10+ nameSpaces and 20+ dragular boxes.  When init is called, it's really hard to determine which one its for.
Currently doing this (simplified):
```javascript
$scope.dragularOptions[key] = { ... , key: key };
$scope.dragularOptions[key].onInit = setDrake($scope.dragularOptions[key]);
function setDrake(options) {
    //need to use closure so can figure out which instance of drake this belongs to
    return function(drake) {
        $scope.drakeOptions[options.key] = drake;
    };
}
```

It would be nice if the onInit would could send the options as the second parameter.

**Comment by luckylooke** [comment]
> It would be nice if the onInit would could send the options as the second parameter.
Can make it that way.. I will be fixing bugs soon, I will add this improvement into code then.

**Comment by luckylooke** [comment]
@phazei implemented, will be in next release ;)
