### ISSUE TITLE
angular directives won't work when copy

### ISSUE THREAD

**Issue by flick36** [luckylooke/dragular#71]

**Comment by flick36** [comment]
Actually it's werid sometimes works sometime doesn't

![animation](https://cloud.githubusercontent.com/assets/8582529/13626570/beb69ab8-e588-11e5-828d-5d9a221b88d3.gif)

**Comment by luckylooke** [comment]
Please provide a codepen of situation so I can investigate the problem, thanks!

**Comment by flick36** [comment]
Here: http://codepen.io/anon/pen/vGGqpJ

notice how the 'Lemon' div has a ng-click function that calls a function in the controller, when i move it to the other container it gets copied but the new element wont trigger de ng-click, I have read and when u copy or add elements to the DOM you should $compile the element.

**Comment by luckylooke** [comment]
Nice catch! Thanks for pointing me to this issue, I will fix it soon ;)

**Comment by luckylooke** [comment]
Now its working with new options.compileItemOnDrop. It is not going to be default behavior as in use-cases with ng-repead it is unwanted behavior. In such cases items elements are rendered by ng-repead so directives should be defined in template and controlled by inner logic. 

Codepen: http://codepen.io/anon/pen/NNRjOd

**Comment by luckylooke** [comment]
I have noticed flickering caused by accept function.. I will investigate it later.
