### ISSUE TITLE
removeOnSpill doesn't remove from Model

### ISSUE THREAD

**Issue by flick36** [luckylooke/dragular#74]
As the title says, the removeOnSpill doesnt remove the item from the containers Models, whe nyou ar eusing Models, of course...

http://i.imgur.com/BU59ba0.gif

**Comment by luckylooke** [comment]
Please create codepen with the issue, I cannot replicate it. In examples it is working just fine: http://luckylooke.github.io/dragular/#/docs/exampleRemoveOnSpillWithModel

**Comment by luckylooke** [comment]
Seems to be no more actual..
