### ISSUE TITLE
Trying to create a destkop on dragula and angular2

### ISSUE THREAD

**Issue by mburger81** [luckylooke/dragular#76]
Hey, sorry for writing you here.

I need some help, I'm trying to do a complicate drag&drop with angula 2 beta.9 and ng2-dragula which uses dragula.

Look at this not working example.
http://jsbin.com/yutifozini/edit?html,css,js,output

There are a menu with three sub-menus, they should not be draggable but droppable.

Than I have  three big containers, this containers should be draggable and droppable each other and the container should be also draggable in the submenue

Each of the containers, contain four widgets, this widgets also I need to drag into the sub-menu, so it should be droppable into sub-menu but not draggable each other.

I'm trying to make a normal desktop behaviour in the browser, and I will store my widgets into the Menus by simple drag&drop it into the Menu. Also i need to Drag&Drop the big container into a Menu, but also I need to change position of the containers in my view. Doing this with dragula is a thrill!

I hope I was able to explain it, du you think I can do something like that with your lib. If it works I'll wrap it into an angular2 lib.

thx
  Michael

**Comment by luckylooke** [comment]
You have so many rules... and it is a bit messy for me...  please try to split it into partial problems.. we will try to solve them one by one ok?

**Comment by luckylooke** [comment]
Seems to be no more actual..
