### ISSUE TITLE
dragular came as a empty object when using es6 import

### ISSUE THREAD

**Issue by blackendstudios** [luckylooke/dragular#78]
hi, well, I saw your update by using webpack, I'm using it too, so in the past to make it work I had to extracted the concatenated file in a folder a putting it export default at the end, due browserify stuff,  it really worked just like that, but now I want to try the lastest version and importing it but I got an empty object literal..all of the other external libraries work just fine, except this one, I don't want to do the same thing :)

![dragular_import](https://cloud.githubusercontent.com/assets/4050205/13959005/38e50b16-f020-11e5-98fc-9d40012180ff.png)

even with {}. {* from } all of the other es6 import syntax do not work either

**Comment by luckylooke** [comment]
@alferov can you look at it please?

**Comment by alferov** [comment]
@luckylooke Sorry, my bad. It should have been exported as a UMD module (by default webpack exposes it as a global variable https://webpack.github.io/docs/configuration.html#output-librarytarget)

**Comment by luckylooke** [comment]
@blackendstudios please retest

**Comment by blackendstudios** [comment]
@luckylooke yeah, it works now, thank you so much :)

**Comment by luckylooke** [comment]
Great! :)
