### ISSUE TITLE
removeOnSpill not working correctly

### ISSUE THREAD

**Issue by gennext1** [luckylooke/dragular#81]
Hi, 
     I have been facing an issue in dragular drag and drop. I have set removeOnspill to false, even though the values in my container gets removed when dropped in the same container.
![1](https://cloud.githubusercontent.com/assets/17293610/14452126/15deddbe-00aa-11e6-97c1-fdd2e7354284.jpg)
![2](https://cloud.githubusercontent.com/assets/17293610/14452127/15e55cb6-00aa-11e6-9fc0-b32989324713.jpg)

I have attached two screenshots. The image1 contains six daggable values. when i drag and dropped capability1 in same container it got removed, it is displayed as shown in image2. 

The code for DragularService which i used is: 
dragularService('.bdlist', {

            nameSpace:'samplenamespace',
            containersModel : [$scope.capabilities,$scope.allDataCapabilities],
            removeOnSpill : false

        });
Thanks in Advance.

**Comment by luckylooke** [comment]
I will look at it soon, thanks for reporting.

**Comment by luckylooke** [comment]
Hi there! I couldnt reproduce your issue.. could you please reproduce it somewhere in public? Like jsfiddle, codepen, whatever.. so I can investigate your issue. Thanks

**Comment by gennext1** [comment]
Hi, I tried reproducing the issue in JSFiddle but i am facing error in integrating the dragular js files.
Please have a look at my JSFiddle. 
https://jsfiddle.net/Inamulla/pwbdurk6/1/

Thanks.

**Comment by luckylooke** [comment]
I  have make a fork for you: https://jsfiddle.net/b2pqp69z/

**Comment by gennext1** [comment]
Hi,
  I have reproduced the issue in the JSFiddle https://jsfiddle.net/Inamulla/06wgmu7o/5/ 
Please have a look at it. When I was trying to rearrange the items in the dropped container (top container) they get deleted.

Thanks.

**Comment by luckylooke** [comment]
Thank you, I will be working on it.

**Comment by luckylooke** [comment]
Solution: https://jsfiddle.net/06wgmu7o/6/
Comments:
- containers models must be defined before you provide them to dragular service
- removeOnSpill false is by default, you dont need to set it
