### ISSUE TITLE
Filtered model in nested ng-repeat

### ISSUE THREAD

**Issue by GDuchemin** [luckylooke/dragular#83]
Hi luckylooke! 
First of all, thank you for dragular, i love it ;)

I have a problem when I want to allow drag and drop in nested ng-repeat with filter. I don't know how to build multiple `containersFilteredModel` in a nested ng-repeat. In your doc: http://luckylooke.github.io/dragular/#/docs/exampleNgRepeatFilteredWithModel you have only 2 "static" models but it seems broken.

//------UPDATE-------
I want to add and remove object in my filtered ng-repeat collection. What's the best way to update model ? I tried to kill and reload dragular instance, but i have some trouble with drag and drop in few cases.

You can see my problem in this JSFiddle: https://jsfiddle.net/b2pqp69z/1/

nested ng-repeat (by `deadline`) are enable by default in html.

Hope you help me, have a nice day !

**Comment by cieljaune** [comment]
+1

**Comment by luckylooke** [comment]
Oh dear, that seems to be really broken.. so I will fix it soon. And nested-filtered, I havent tried such usecase yet, so probably it will take some time to look at it. Thanks for report and for using dragular ;)

**Comment by GDuchemin** [comment]
Thx for your fast answer ! ;)

I updated my first post for a linked issue. Do you want I open a new one for add and remove items in nested ng-repeat ? As model can't be link to a scope collection, I see no way to update my collection except killing dragular instance and init it again.

Thx again ;)

**Comment by luckylooke** [comment]
Yes, it sounds good to separate issues. Filtered model in nested ng-repeat is more like feature request and broken example is bug for sure. ;)

**Comment by luckylooke** [comment]
Ok I have found the problem of not working example. It was just copy/paste mistake during @alferov webpack workflow implementation. So library it self works well there. That means that I need to solve the case where nested and filtered are combined. Please open new issue for that case, thanks! ;)
