### ISSUE TITLE
Using jspm, I get a css.js 404 error

### ISSUE THREAD

**Issue by breity** [luckylooke/dragular#85]
Hey, thanks for this great library! I'm trying to install it with jspm and I get this error when importing dragular to our application:

`system.src.js:4892 GET http://[path-to-app-dir]/css.js 404 (Not Found)`

Any idea what's causing this?  Thanks again.

**Comment by luckylooke** [comment]
I am dont know jspm, try to solve it, if you are familiar to jspm. Thanks

**Comment by luckylooke** [comment]
Closing as inactive..
