### ISSUE TITLE
Can't click on buttons & inputs

### ISSUE THREAD

**Issue by forcewill** [luckylooke/dragular#87]
I cannot click on any buttons and inputs inside a container.

**Comment by luckylooke** [comment]
Please try to reproduce your scenario at jsfiddle, codepen or wherever online so I can investigate. I have made quick test and everything seems to be working. http://prntscr.com/b3cfwc

**Comment by luckylooke** [comment]
Closing due to idle.

**Comment by DiegoHuang** [comment]
Hi luckylooke, 
I face the same problem in example "NestedNgRepeat",  input field doesnt work on the second nested "exampleCell".

**Comment by luckylooke** [comment]
@DiegoHuang I have found the problem, thanks for reporting, fixed in v4.2.4 ;)

**Comment by DiegoHuang** [comment]
It work well now, thank you! ：)
