### ISSUE TITLE
Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by forcewill** [luckylooke/dragular#88]
I get this error from time to time:
`Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.     at Error (native)`

when dragging a lot of items from one container to another one by one.

**Comment by luckylooke** [comment]
Hmm.. I was testing this on some examples in DEMO page and havent noticed such error. Could you please try to get more info about circumstances when error is occured? Thanks

**Comment by luckylooke** [comment]
Closing due to idle.
