### ISSUE TITLE
Example NestedNgRepeatWithModel

### ISSUE THREAD

**Issue by christophertrudel** [luckylooke/dragular#89]
http://luckylooke.github.io/dragular/#/docs/exampleNestedNgRepeatWithModel

Is it possible with this example to drag an item outside of the row and NOT be placed inside a row but instead exist on the same level as the row and vice versa?  Example below, currently you can drag **Item 5**  from **Row 2** to  **Row 1** but I would also like to drag it outside of a row or from outside a row back into a row. Is this possible?

- row 1
   - item 1
   - item 2
   - item 3

- item 5

- row 2
   - item 4
   - item 6

**Comment by christophertrudel** [comment]
Never mind, after playing around with it I realized this can be achieved without using name spacing.

**Comment by luckylooke** [comment]
I am glad you have find the way ;)
