### ISSUE TITLE
nested ng-repeat disturb drag'n drop

### ISSUE THREAD

**Issue by AndrinGautschi** [luckylooke/dragular#91]
I try to generate a plan with flexible number of rows and columns. In fact, this is a 2D Array. Dragular works fine when there is just one hard coded row with a single ng-repeat, which generates the columns. But it stops working when I build around a ng-repeat which should generate the rows.

Have a nice day.

**Comment by GDuchemin** [comment]
Maybe same issue : https://github.com/luckylooke/dragular/issues/84
I have an issue with nested ng-repeat, during developing a 2D planning too.

**Comment by luckylooke** [comment]
There is an example of nested repeats: http://luckylooke.github.io/dragular/#/docs/exampleNestedNgRepeatWithModel

If it doesn't help please reopen.
