### ISSUE TITLE
Nested ng-repeat with models between directives

### ISSUE THREAD

**Issue by jweinstein92** [luckylooke/dragular#92]
I am attempting to replicate the nested ng-repeat with model example, but through different directives.

Pretty much, I have a list of contacts and groups of contacts. I would like to move these contacts into a separate container but make moving the groups disabled. I have a directive for the containers, a directive for contacts, and then a directive for groups.

I feel like I am close - I can add a Contact to a container and drag a GroupContact into the container. However when I drag the GroupContact into the container, the container model isn't updated with the GroupContact's information. I also get an 
```
dragular.js:1182 Uncaught TypeError: Cannot read property 'nextElementSibling' of null

v	@	dragular.js:1182
Q	@	dragular.js:796
o	@	dragular.js:816
V	@	dragular.js:804
B	@	dragular.js:418
```

I added a drop callback which i outputted the arguments of the drop event and I believe the issue has something to do with scopes.

**Comment by luckylooke** [comment]
Can you replicate your issue somewhere public? Like jsfiddle, codepen..etc.. thanks. You can reuse code from other issue like this one: https://jsfiddle.net/hLsuege1/.

**Comment by luckylooke** [comment]
Closed due to inactivity
