### ISSUE TITLE
Items disapear after drop and model not updated

### ISSUE THREAD

**Issue by catamaican** [luckylooke/dragular#93]
Hi,

it's very very strange: in my controller I have somthing like this:

`        $scope.ListaSpecializariNealeseInfo = [{ "IdGrupDS": "cbb277e0-afcc-4c31-a76f-dc0853556ba8", "Id": "bf207d10-f35f-4a56-9504-a8853e9a7f85", "Denumire": "Cai ferate, drumuri si poduri", "TipLoc": null, "PortalId": 23, "IdSesiune": "fbf02383-498e-4be5-9daa-bcb2252f1b76", "TipLocuri": "B", "DenumireCompleta": "Cai ferate, drumuri si poduri (Buget)" }, { "IdGrupDS": "eaf670e1-4077-4a46-a21d-6bcbbccf44ab", "Id": "0d4cc951-4a43-4d67-be0e-af171aa7c898", "Denumire": "Cai ferate, drumuri si poduri", "TipLoc": null, "PortalId": 23, "IdSesiune": "fbf02383-498e-4be5-9daa-bcb2252f1b76", "TipLocuri": "T", "DenumireCompleta": "Cai ferate, drumuri si poduri (Taxa)" }, { "IdGrupDS": "df6eff47-9433-48e1-94d5-dfb6801e9705", "Id": "e7e259f5-2f0f-4006-8bc8-f4e881653dfd", "Denumire": "Instalatii pentru constructii", "TipLoc": null, "PortalId": 23, "IdSesiune": "fbf02383-498e-4be5-9daa-bcb2252f1b76", "TipLocuri": "T", "DenumireCompleta": "Instalatii pentru constructii (Taxa)" }];
        $scope.ListaSpecializariAleseInfo = [{ "IdGrupDS": "6b0b46e2-3079-44fd-b7e9-55fe300d767b", "Id": "98e5b9f4-6dfe-4a7d-ae49-593d265d22a1", "Denumire": "Constructii civile, industriale si agricole", "TipLoc": null, "PortalId": 23, "IdSesiune": "fbf02383-498e-4be5-9daa-bcb2252f1b76", "TipLocuri": "B", "DenumireCompleta": "Constructii civile, industriale si agricole (Buget)" }, { "IdGrupDS": "3ae41cc1-360e-4dd6-9bcb-3fb00db39cb6", "Id": "c1376bf1-23d6-42d2-9fa0-3d014167ecb9", "Denumire": "Constructii civile, industriale si agricole", "TipLoc": null, "PortalId": 23, "IdSesiune": "fbf02383-498e-4be5-9daa-bcb2252f1b76", "TipLocuri": "T", "DenumireCompleta": "Constructii civile, industriale si agricole (Taxa)" }, { "IdGrupDS": "371fdec1-da5f-4133-aae2-bb4831b69409", "Id": "847c46ac-27e2-49ba-b6fc-a49dba22bdbd", "Denumire": "Instalatii pentru constructii", "TipLoc": null, "PortalId": 23, "IdSesiune": "fbf02383-498e-4be5-9daa-bcb2252f1b76", "TipLocuri": "B", "DenumireCompleta": "Instalatii pentru constructii (Buget)" }];
`

and the html temple:

`    <div class="row" style="float:none">
        <div class="tableRow">
            <div class='containerDD' dragular='{"nameSpace":"common"}' dragular-model='ListaSpecializariNealeseInfo'>
                <div ng-repeat='item in ListaSpecializariNealeseInfo' ng-bind='item.DenumireCompleta'></div>
            </div>
            <div class='containerDD' dragular='{"nameSpace":"common"}' dragular-model='ListaSpecializariAleseInfo'>
                <div ng-repeat='item in ListaSpecializariAleseInfo' ng-bind='item.DenumireCompleta'></div>
            </div>
        </div>
    </div>
    {{ListaSpecializariNealeseInfo}}
    <hr />
    {{ListaSpecializariAleseInfo}}`
and this work, because $scope.ListaSpecializariNealeseInfo and ListaSpecializariAleseInfo are hardcoded in the entry-code in the module.

BUT, when the data comes from the database (after clicking/interacting with the application)
`$scope.ListaSpecializariNealese = function () {
        factory.callGetService("ListaSpecializariNealese?idGrup=" + $scope.CandidatInfo.IdGrupTemp + "&IdCandidatFacultate=" + $scope.CandidatInfo.IdCandidat + "&IdSesiune=" + $scope.CandidatInfo.IdSesiune + "&PortalId=-1" + "&AfiseazaToateOptiunileBT=true")
            .then(function (response) {
                var fullResult = angular.fromJson(response);

                $scope.ListaSpecializariNealeseInfo = fullResult.data;

                console.log("ListaSpecializariNealese: " + $scope.ListaSpecializariNealeseInfo);

            },
                function (data) {
                    console.log("Unknown error occurred calling ListaSpecializariNealese");
                    console.log(data);
                });
    };`
, when I try to drag/drop items, they just disappear. AND, the model is not updated for both containers, similar to the image below. Please note there the model (which is not updated) and the "missing" items from the models

![clipboard01](https://cloud.githubusercontent.com/assets/18305539/16453021/f4ffb6fc-3e13-11e6-9f95-d0d735ae6b24.jpg)

**Comment by catamaican** [comment]
similar with https://github.com/bevacqua/angular-dragula/issues/78

**Comment by luckylooke** [comment]
Your post is very messy to me, I can hardly oriented there. Can you replicate your issue somewhere public? Like jsfiddle, codepen..etc.. thanks. You can reuse code from other issue like this one: https://jsfiddle.net/hLsuege1/.

**Comment by catamaican** [comment]
somehow i've missed https://github.com/luckylooke/dragular/issues/47 and I just null-ed the arrays containing the data. My solution was to display the container with ng-if using a timeout after the source arrays where populated with new data from api, something like this:

```
factory.callGetService("ListaSpecializariNealese")
                .then(function (response) {
                    var fullResult = angular.fromJson(response);

                    $scope.RenderDirective = false;

                    $scope.ListaSpecializariNealeseInfo = fullResult.data;

    $timeout(function () {
                        $scope.RenderDirective = true;
                    }, 100);
```
