### ISSUE TITLE
Events documentation wrong

### ISSUE THREAD

**Issue by ipavlic** [luckylooke/dragular#94]
It seems the events documentation on github.com/luckylooke/dragular is wrong. Instead of `el, container` parameters as it states, dragular appears to be providing `event, element` instead.

**Comment by luckylooke** [comment]
Yes, parameters are prepended by angular, so first parameter is always event object. But you're right it could be mentioned in docs.. I will put it there. Thanks for notice!

**Comment by ipavlic** [comment]
It's _already_ in the docs but it's documented wrongly.

**Comment by luckylooke** [comment]
Yes, I was meaning the first parameter added automaticaly by angular.. I have corrected it moment ago and also augmented missing parts of table ;)
