### ISSUE TITLE
Pass original DOM event objects along other parameters on dragular events

### ISSUE THREAD

**Issue by ipavlic** [luckylooke/dragular#97]
How can I get the event position from any event? For example, `dragulardrag`'s listener gets the `event` parameter, but it doesn't seem to be a touch (or click) event, so I can't seem to get information on position from that.

**Comment by luckylooke** [comment]
Youre right, Event object passed is from angular library, more on that object [here](https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$on). If you tell me usecase I can add it to API. For now you can access such information from unofficial developer API via service `dragularService.shared`.
Looks like this:
```
classesCache: {}, // classes lookup cache
  containersCtx: {}, // containers model
  containers: {}, // containers
  mirror: null, // mirror image
  source: null, // source container
  item: null, // item being dragged
  copy: null, // copy flag
  sourceItem: null, // item originaly dragged if copy is enabled
  sourceModel: null, // source container model
  sourceFilteredModel: null, // source container filtered model if relevant
  target: null, // droppable container under drag item
  targetCtx: null, // target container context
  targetModel: null, // target container model
  lastDropTarget: null, // last container item was over
  offsetX: null, // reference x
  offsetY: null, // reference y
  moveX: null, // reference move x
  moveY: null, // reference move y
  offsetXr: null, // reference x right for boundingBox feature
  offsetYb: null, // reference y bottom for boundingBox feature
  clientX: null, // cache client x, init at grab, update at drag
  clientY: null, // cache client y, init at grab, update at drag
  mirrorWidth: null, // mirror width for boundingBox feature
  mirrorHeight: null, // mirror height for boundingBox feature
  initialSibling: null, // reference sibling when grabbed
  currentSibling: null, // reference sibling now
  initialIndex: null, // reference model index when grabbed
  currentIndex: null, // reference model index now
  tempModel: null, // if o.isContainer is used, model can be provided as well, it is temporary saved here during drags
  dragOverEvents: {}, // drag over events fired on element behind cursor
  lastElementBehindCursor: null, // last element behind cursor
  grabbed: null // holds mousedown context until first mousemove
```
But this API isnt garanted to remain same in future!!!

**Comment by ipavlic** [comment]
So sorry for not responding sooner. The use case is when dragging elements which are not lists, to be able to tell where exactly they landed and then be able to perform some visualisation based on that. I'll close this for now, but adding this to the API would be very useful.

**Comment by luckylooke** [comment]
So returning original event as well on dragulardrag as parameter for listener would be acceptable solution for you?

**Comment by ipavlic** [comment]
I believe so, yes.

**Comment by luckylooke** [comment]
I will implement in next release.

**Comment by ipavlic** [comment]
Great! Do you have an estimated timeframe?

**Comment by luckylooke** [comment]
Next week I supose.

Dňa 3.8.2016 15:16 používateľ "Ilija Pavlic" <notifications@github.com>
napísal:

**Comment by luckylooke** [comment]
Done ;)
