### ISSUE TITLE
Error in the console

### ISSUE THREAD

**Issue by cocaux** [luckylooke/dragular#98]
Hi @luckylooke, 

I would like to be able to enable and disable the drag n drop by clicking on a button. I set up my container on the first click and remove it by using dragularService.cleanEnviroment(). It works fine but I noticed that I get some errors in the console log:

1. Once the container has been set up, If I drag a children out of it, I got:
dragular.js:1280 Uncaught TypeError: Cannot read property 'parentNode' of null

2. Once the container has been removed of the service, if I click on it, I got:
dragular.js:468 Uncaught TypeError: Cannot read property 'indexOf' of undefined

My container options are really simple:
dragularService('#container', {
        classes: {
          transit: 'reorder-transit'
        },
        containersModel: [list]
      });

Did I miss something some options ?
Thanks for your help.

**Comment by luckylooke** [comment]
Can you replicate your issue somewhere public? Like jsfiddle, codepen..etc.. so I can better investigate, thanks. You can reuse code from other issue like this one: https://jsfiddle.net/hLsuege1/.

**Comment by cocaux** [comment]
Here is an example:
https://jsfiddle.net/L02g8ado/1/
I think to reproduce the first case, you need to enable, disable and enable and then drag outside.

Let me know if you need more info.

**Comment by luckylooke** [comment]
Reinitialisation is not effective and clearEnviroment was method created for dev purposes. I have edited your code. Notice `moves` property in options. https://jsfiddle.net/L02g8ado/3/

**Comment by cocaux** [comment]
Thanks!

**Comment by cocaux** [comment]
@luckylooke, I noticed that if I reset the list then when I drag n drop the item disappears. 
I updated the jsfiddle: https://jsfiddle.net/cocaux/L02g8ado/4/
Step to reproduce:
1. Click on Enable
2. Drag & Drop items
3. Click on Reset
4. Drag & Drop items, they disappeared.

Thanks

**Comment by luckylooke** [comment]
Updated fiddle: https://jsfiddle.net/L02g8ado/5/

Hint: js keeps reference instead of value for non-primitive types, so you cannot destroy array you provided to dragular on init, you must edit the initial one.

**Comment by cocaux** [comment]
Thanks for your help :)
